### ISSUE TITLE
[Bug] Wallet Connect - Fireblocks

### ISSUE THREAD

**Issue by Calcifer1001** [near/wallet-selector#1004]
**Describe the bug**

After logging in using wallet connect and fireblocks, any time I try to do a transaction of any sort I get the error `Uncaught (in promise) {code: -32000, message: 'Server error'}`

**Steps To Reproduce**å

_Steps to reproduce the behavior:_

1. Go to https://fireblocks-minimalist-test.vercel.app/
2. Click on `Connect`
3. Choose Wallet connect and scan the QR code using a fireblocks testnet account
4. When finishing log in, click on `Stake 1 NEAR`
5. Check the console

_Error description_

It is expected to get a QR code to scan with fireblocks and stake 1 NEAR

**Screenshots**

![image](https://github.com/near/wallet-selector/assets/83971551/d5401621-93d0-466e-a75b-ec9e3ae2a756)

**Desktop**: 
* OS : Linux zorin
* Browser : Chrome
* Browser Version :  Version 119.0.6045.105 (Official Build) (64-bit)

**Additional Context**

In order to make this simpler, I've created [this](https://github.com/Meta-Pool/fireblocks-minimalist-test) minimalist example. The vercel link above points to the same repo. 

To replicate the real scenario, I left the @near-wallet-selector/wallet-connect version to "6.0.0" since when updating it into the real project has an error and when using the newest in this minimalist example I get another error, telling `Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://verify.walletconnect.com')  does not match the recipient window's origin ('https://fireblocks-minimalist-test.vercel.app')` when clicking on `Wallet connect` in the modal

**Comment by kujtimprenkuSQA** [comment]
Hi, @Calcifer1001 thanks for raising this issue.

> updating it into the real project has an error and when using the newest in this minimalist example I get another error, telling Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://verify.walletconnect.com')  does not match the recipient window's origin ('https://fireblocks-minimalist-test.vercel.app') when clicking on Wallet connect in the modal

This error can be ignored or you can verify your domain in WalletConnect https://cloud.walletconnect.com/app - Click Project Id then Domain verification

We would appreciate it if you create a demo with a version of @near-wallet-selector/wallet-connect `v7.0.3` or higher since any version lower than 7.0.0 is not implemented according to the bridge wallets standard.

**Comment by kujtimprenkuSQA** [comment]
> 3. Choose Wallet connect and scan the QR code using a fireblocks testnet account

How can we get a Fireblocks testnet account?

**Comment by kujtimprenkuSQA** [comment]
> It is expected to get a QR code to scan with fireblocks and stake 1 NEAR

When you are connected with a wallet with WalletConnect you only get prompted with the QR code to connect with that wallet and not every time you `signAndSendTransaction(s)` once the `near_signAndSendTransaction` or `near_signAndSendTransaction` is triggered with a transaction that needs confirmation, the wallet should automatically prompt you to confirm.

**Comment by Calcifer1001** [comment]
I'll try what you suggested. 

Regarding fireblocks, you should be able to get a testnet account [here](https://www.fireblocks.com/request-demo)

**Comment by kujtimprenkuSQA** [comment]
> I'll try what you suggested.
> 
> Regarding fireblocks, you should be able to get a testnet account [here](https://www.fireblocks.com/request-demo)

Hi, while I wait for Fireblocks to activate the account for me.

I tested your demo with the web-examples of WalletConnect where we added support for NEAR:
Wallet Example (testnet): https://react-wallet.walletconnect.com/
_you might need to switch to settings tab and enable testnets_

I noticed that in the transaction to stake 1 NEAR the `receiverId` is missing:

 
![sign-transaction](https://github.com/near/wallet-selector/assets/95851345/ebdec25b-6aea-4653-87d6-816c660f887b)

**Comment by kieranbop1990** [comment]
I am seeing this exact issue too. I pulled down the examples repository and installed and set my Wallet connect ID but I can't even get it to form a connection.

**Comment by kujtimprenkuSQA** [comment]
Here's a video trying out this example provided above: https://fireblocks-minimalist-test.vercel.app/

[demo.webm](https://github.com/near/wallet-selector/assets/95851345/837c6890-56b4-45a0-b4be-fa2bed9a3d88)

**Comment by kujtimprenkuSQA** [comment]
> I am seeing this exact issue too. I pulled down the examples repository and installed and set my Wallet connect ID but I can't even get it to form a connection.

What examples repository have you pulled down?

**Comment by kieranbop1990** [comment]
Hey @kujtimprenkuSQA . I am using the react app in the examples for the wallet-connector. When I try and connect to fireblocks it just shows rejected. I see your dependency bump. I will try that now.

**Comment by kujtimprenkuSQA** [comment]
> Hey @kujtimprenkuSQA . I am using the react app in the examples for the wallet-connector. When I try and connect to fireblocks it just shows rejected. I see your dependency bump. I will try that now.

Hi, can you move to this branch locally: https://github.com/near/wallet-selector/tree/bump-wallet-connect-deps

1. run: `yarn && yarn build:all`
2. Set WalletConnect projectId [here](https://github.com/near/wallet-selector/blob/bump-wallet-connect-deps/examples/react/contexts/WalletSelectorContext.tsx#L89)
3. run `yarn nx serve react`

Try connecting the fireblocks wallet again.

If this does not work could you remove [near_signMessage](https://github.com/near/wallet-selector/blob/bump-wallet-connect-deps/packages/wallet-connect/src/lib/wallet-connect.ts#L76) method and refresh the example and try to connect again and see if this is causing any issues.

I will see to find a way to get a Fireblocks account and troubleshoot it asap.

**Comment by kujtimprenkuSQA** [comment]
We just published a new version of wallet selector `v8.7.2` in which we bumped the WalletConnect dependencies to the latest version, can you try it with this version and see how it goes?

Tested WalletConnect option with https://react-wallet.walletconnect.com/ and https://optowallet.com/ (now deprecated, but still works fine) wallet-connect option is working fine with these two.

>Note: We did not change any functionality on our side in the wallet-connect option with the exception of adding a new method near_signMessage which should not be a breaking change unless Fireblocks has some specific implementation that does not allow new methods.

---
We have applied for an account in Fireblocks but we never got any reply from them, is there any other way we could get an account?

**Comment by kujtimprenkuSQA** [comment]
Hi, @Calcifer1001 & @kieranbop1990 have you tested the latest version of Wallet Selector, are you still having issues with Fireblocks?

**Comment by kujtimprenkuSQA** [comment]
I have requested a demo from Fireblocks multiple times and have emailed them this week, still waiting for a response from them.

**Comment by AmmarHumackicSQA** [comment]
> Hi, @Calcifer1001 & @kieranbop1990 have you tested the latest version of Wallet Selector, are you still having issues with Fireblocks?

Hi @Calcifer1001 @kieranbop1990 any news regarding this 👆 ? Thanks!

**Comment by AmmarHumackicSQA** [comment]
Hi @Calcifer1001  @kieranbop1990 , I will close this issue for now, as there has been no reply for a while. Feel free to reopen it. Thanks!
