### ISSUE TITLE
Sign and send transaction to MyNearWallet loses Promise<FinalExecutionOutcome>

### ISSUE THREAD

**Issue by PierreLeGuen** [near/wallet-selector#1057]
**Describe the bug**

SignAndSendTransaction for MyNearWallet redirects to MyNearWallet app causing the currently running app to lose state/memory of the wallet selector. This is causing issues when you want to act based on the promise result. 

**Steps To Reproduce**å

_Steps to reproduce the behavior:_

1. SignAndSend any transaction to MNW
2. await on the promise
3. console.log(...) after the promise. The console log will never be triggered.

_Error description_

**Expected behavior**

Keep state and resolve the promise.

**Comment by kujtimprenkuSQA** [comment]
Hi @PierreLeGuen thank you for raising this issue.

This is the default behavior of browser wallets for transactions that attach any deposit or non-function-call actions because these transactions can not be signed with a limited access key and need to be signed with the `full-access-key` on the wallet.

**Comment by PierreLeGuen** [comment]
Understood, but how are we supposed to handle transaction approval after redirect on app side?

**Comment by PierreLeGuen** [comment]
Maybe you could open the sign page in an other tab/window and poll rpc for transaction status?

**Comment by kujtimprenkuSQA** [comment]
The wallet will add the `transactionHashes` query param into the `callbackUrl` of `signAndSendTransaction(s)`:

For example something like this:
https://near.github.io/wallet-selector/?transactionHashes=6EgAkd1iKTzEdyx8E8cn7Kocv6Go24SCG6hED6BgBSii

In your dApp you could check the txStatus:

```ts
const provider = new providers.JsonRpcProvider({ url: network.nodeUrl });
const txHash = "6EgAkd1iKTzEdyx8E8cn7Kocv6Go24SCG6hED6BgBSii";
const accountId = "kujtimp.testnet";
const result = await provider.txStatus(txHash, accountId);
console.log("Execution Outcome Result: ", result);

```

**Comment by kujtimprenkuSQA** [comment]
@PierreLeGuen we're closing the issue for now, if you have any other questions feel free to re-open the issue.
