### ISSUE TITLE
[Defect] Can't connect using wallet connect

### ISSUE THREAD

**Issue by Calcifer1001** [near/wallet-selector#1060]
**Describe the bug**

**Steps To Reproduce**å

_Steps to reproduce the behavior:_

1. Go to https://www.metapool.app/stake?token=near
2. Click on 'Connect your wallet'
3. Select 'Wallet connect'
4.  Scan the QR code with any app like trust wallet or fireblocks.

_Error description_
A ver generic error: 'Failed to sign in with WalletConnect: Something went wrong'

**Expected behavior**

To log into the account, seeing on top right things like balance.

**Screenshots**

![image](https://github.com/near/wallet-selector/assets/83971551/bb101676-498e-42a8-b405-40be88e94ed6)

**Desktop**: 
* OS : Linux zorin (and others os) 
* Browser :  google chrome
* Browser Version :  121.0.6167.85 (Official Build) (64-bit)

**Additional Context**

Checking the wallet connect documentation, seems like on near-wallet-selector/wallet-connect/index.js there is a variable WC_METHODS that include 2 methods "near_verifyOwner", "near_signMessage" that are supposed to be optional. Removing them didn't solve the issue, but might be related

**Comment by kujtimprenkuSQA** [comment]
Hi, @Calcifer1001 thank you for raising this issue.

I downloaded the Trust Wallet on iOS app store and created a new NEAR account then tried connecting via WalletConnect but it looks like NEAR + WalletConnect is not supported on this wallet yet:


https://github.com/near/wallet-selector/assets/95851345/6016f3f7-2f54-47ef-9281-0cf7fcc9cb37

The error message returned is: 
![image](https://github.com/near/wallet-selector/assets/95851345/f611907a-4298-4eca-a300-3d78f4ff7e76)


---

How can I test it with Fireblocks?

**Comment by Calcifer1001** [comment]
Have you tried another method? As far as I know, you don't own a fireblocks account, and I'm not able to provide you with one unfortunatelly. Is there another wallet that can use wallet connect to test this?

Thanks

**Comment by Calcifer1001** [comment]
Just found out you can use here wallet to log into WC. Yet, it is not working. You can try with that

**Comment by kujtimprenkuSQA** [comment]
Checked the HERE Wallet but it does not look like they support NEAR (`near` namespace) through WalletConnect:

![image](https://github.com/near/wallet-selector/assets/95851345/2595c439-c7c1-467d-ad24-53ecfce76519)

---

This is a working wallet example `testnet` only:
https://react-wallet.walletconnect.com/

We are not aware of any other official wallet that supports WalletConnect + NEAR based on the [Bridge Wallets Standard](https://github.com/near/NEPs/blob/master/specs/Standards/Wallets/BridgeWallets.md)

**Comment by kujtimprenkuSQA** [comment]
@Calcifer1001 We got information that WalletConnect in HERE Wallet is used to connect with Aurora.

**Comment by Calcifer1001** [comment]
I was told it was possible. Seems the only one is fireblocks for now. I was able to get you an account, but an email is required. Can you provide me with one?

**Comment by kujtimprenkuSQA** [comment]
> I was told it was possible. Seems the only one is fireblocks for now. We were able to get you an account, but an email is required. Can you provide me with one?

Hi, please send all instructions to `Kujtim.Prenku@sqa-consulting.com`

**Comment by Calcifer1001** [comment]
Great! Let me know if I can assist you with anything

**Comment by kujtimprenkuSQA** [comment]
Hi, we made some changes to the wallet-connect package, and now from the next version it's possible to override the `methods` and `events` from the dApp side in [setupWalletConnect](https://github.com/near/wallet-selector/blob/dev/examples/angular/src/app/pages/wallet-selector/wallet-selector.component.ts#L79-L85).

I deployed these changes in `gh-pages`,  can you please try connecting with Fireblocks and see if you can connect successfully?

My account still needs to be approved by the owner so when I try to connect I can not sign transactions and see this error:

![image](https://github.com/near/wallet-selector/assets/95851345/933c183b-148f-44a5-8817-702df81e5bb5)

**Comment by kujtimprenkuSQA** [comment]
You cant test the connection on this dApp:

https://react-app.walletconnect.com/

- Enable testnets
- Click NEAR Testnet option
- Connect

**Comment by Calcifer1001** [comment]
When following the instructions you shared for the link: https://react-app.walletconnect.com/ I get an error telling me the QR code does not belong to fireblocks. In some sense it makes sense, yet, I've always logged in with the Wallet Connect QR code, so at the same time it doesn't make sense. 

You said it was deployed in the gh-pages. Does this mean there is a new version I can try in our code? 

Thanks for your help!

**Comment by kujtimprenkuSQA** [comment]
> When following the instructions you shared for the link: https://react-app.walletconnect.com/ I get an error telling me the QR code does not belong to fireblocks. In some sense it makes sense, yet, I've always logged in with the Wallet Connect QR code, so at the same time it doesn't make sense.
> 
> You said it was deployed in the gh-pages. Does this mean there is a new version I can try in our code?
> 
> Thanks for your help!

Can you try to update the wallet-selector to the latest version `v8.9.4` in your dApp and provide these [methods](https://github.com/near/wallet-selector/blob/dev/examples/angular/src/app/pages/wallet-selector/wallet-selector.component.ts#L79-L85) to the `setupWalletConnect`?

**Comment by kujtimprenkuSQA** [comment]
With the change included in release `v8.9.4` specifically on this PR: https://github.com/near/wallet-selector/pull/1068 there should be no problems connecting Fireblocks with WalletConnect option.

Here are two videos that at least demo the `connection` part I have to emphasize it again since my Fireblocks account does not allow me to sign transactions that's the reason I commented the `requestSignIn` in the videos below:

From desktop:

[fireblocks_desktop.webm](https://github.com/near/wallet-selector/assets/95851345/5473f6b2-40b8-4e71-94ba-0d463ba896dd)

From mobile phone (same video):


https://github.com/near/wallet-selector/assets/95851345/2d1ddacb-2dad-4c6d-8a1d-07f1d44f57c9

---

I am going to go ahead and close the issue for now, if you still have problems connecting to Fireblocks feel free to re-open it.
