### ISSUE TITLE
[Problem] Remove NEAR Wallet from wallet-selector

### ISSUE THREAD

**Issue by sainthiago** [near/wallet-selector#1071]
**Describe the bug**

Since NEAR Wallet is not being supported and working anymore, should be removed from wallet-selector.

**Comment by kujtimprenkuSQA** [comment]
Hi, thanks for raising this issue.

The `near-wallet` has already been removed in this PR: https://github.com/near/wallet-selector/pull/1066 , today we're making a new release and all changes will be merged into the main branch.

We have already deprecated it on NPM: https://www.npmjs.com/package/@near-wallet-selector/near-wallet

**Comment by kujtimprenkuSQA** [comment]
Closing this issue as the release is out now: https://github.com/near/wallet-selector/releases/tag/v8.9.4
