### ISSUE TITLE
[Defect] Losing connection after page refresh (here-wallet)

### ISSUE THREAD

**Issue by wpdas** [near/wallet-selector#1074]
**Describe the bug**

After connecting my wallet using HERE Wallet, everything works fine until I refresh the page. 

I can see a new item `herewallet:keystore`  added to Local Storage storing the account's info, but the Wallet Selector cannot detect it.

It works if I manually add an item to Local Storage like this (MyNearWallet does it automatically):
```
key: near-api-js:keystore:<account_id>:testnet
value: ed25519:<account_key>
```

**Steps To Reproduce**

_Steps to reproduce the behavior:_

1. Go to any dApp using Here Wallet
2. Connect your wallet
3. Check if you are connected
4. Refresh the page
5. Wallet is not connected anymore

_Error description_

**Expected behavior**

It is expected that the wallet will still connect.

**Desktop**: 
* OS : macOS
* Browser : Chrome / Safari

**Comment by kujtimprenkuSQA** [comment]
Just tested it on https://near.org/ and https://near.social/ and it seems to be working on these two dApps.

**Comment by wpdas** [comment]
> Hi, thank you for raising this issue.
> 
> Just tested it on our guest-book example: https://near.github.io/wallet-selector/ even after page refresh the wallet-selector is still in a `signed-in` state.
> 
> Can you please share the dApp that the issue is happening?
> 
> Also just noticed that HERE Wallet iOS app was updated and now I can't sign transactions that require confirmation on the wallet.

Thank you for the quick response. Let me check if this is because of this iOS update situation. I'll do more tests here and also check if this is something on my implementation.

**Comment by wpdas** [comment]
@kujtimprenkuSQA I found the issue. It was something on my dApp. The state to check accounts were being called twice. Sorry for this.

Thank you for your support.
