### ISSUE TITLE
Integrate support for FailOverRpcProvider into wallet-selector

### ISSUE THREAD

**Issue by charleslavon** [near/wallet-selector#1125]
**Is your feature request related to a problem? Please describe.**
Wallet-selector is currently hardcoded to use a single RPCProvider per network - `https://rpc.mainnet.near.org` and `https://rpc.testnet.near.org`

**Describe the solution you'd like**
Update wallet-selector's initialization method to leverage [FailOverRpcProvider](https://github.com/near/near-api-js/blob/146e516f2d63ac7087ff37ac989e0fb0196715a5/packages/providers/src/failover-rpc-provider.ts#L39) in [setupWalletSelector](https://github.com/near/wallet-selector/blob/01081aefaa3c96ded9f83a23ecf0d210a4b64590/packages/core/src/lib/wallet-selector.ts#L85) and allow developers to [specify multiple RPC Provider URLs](https://github.com/near/wallet-selector/blob/01081aefaa3c96ded9f83a23ecf0d210a4b64590/packages/core/src/lib/options.ts#L10) such that wallet-selector instances can benefit from automatic failover to additional providers given service disruption in the first provider. 

**Acceptance criteria**

- Unit tests should be added which verify the failover behavior
- Examples should be added to demonstrate how one should initialize wallet-selector in order to enable multiple RpcProvider

**Additional context**
FailOverRpcProvider was added into near-api-js [here](https://github.com/near/near-api-js/pull/1334)

**Comment by charleslavon** [comment]
hey @hcho112 @andy-haynes kindly review this request and provide any feedback

**Comment by pivanov** [comment]
done in https://github.com/near/wallet-selector/pull/1153
