### ISSUE TITLE
Add Support for Bundling Images

### ISSUE THREAD

**Issue by lewis-sqa** [near/wallet-selector#142]
## Description

Currently we have to [define images as data URLs](https://github.com/near-projects/wallet-selector/blob/dev/src/wallets/icons.ts) when we want to reference them locally (where previously they referenced a remote server). This task is to implement a bundler that allows us to import images directly.

The suggested bundlers are [Rollup](https://rollupjs.org) and [Webpack](https://webpack.js.org/).

## Acceptance Criteria

- The [`icons.ts` module](https://github.com/near-projects/wallet-selector/blob/dev/src/wallets/icons.ts) is removed.
- Icons for each wallet implementation simply import them similar to any other module.
- NPM scripts are updated to use the bundler instead of `tsc` directly (but maintain both CommonJS and ESM outputs).

**Comment by amirsaran3** [comment]
I tried using Webpack, but I am having some build issues. I will try to make it using Rollup and see how it goes.

**Comment by rgolea** [comment]
This is being fixed by setting the images on a relative folder path in the #196 PR

**Comment by lewis-sqa** [comment]
Fixed as part of #226.
