### ISSUE TITLE
Enhancement: API that sends multiple transactions 

### ISSUE THREAD

**Issue by think-in-universe** [near/wallet-selector#164]
The current version, `near-wallet-selector` supports [`signAndSendTransaction`](https://github.com/near-projects/wallet-selector/blob/06b22086996dc795372969240ee25910fb61b014/src/wallets/Wallet.ts#L58-L60) which sends a single transaction.

I received feedback that developers want to send multiple transactions in some cases. Is this possible to be supported in `near-wallet-selector`?

**Comment by lewis-sqa** [comment]
Ran into a few issues detailed in #170. I've moved this task into blocked until it's clear exactly how it will work for the various wallet implementations.

**Comment by mikedotexe** [comment]
hey @think-in-universe can you help me understand the use case for someone doing multiple transactions?
