### ISSUE TITLE
WalletConnect Support

### ISSUE THREAD

**Issue by AlexBHarley** [near/wallet-selector#264]
Hey, just found out that this repository is looking to add WalletConnect V2 support, awesome!

[Steakwallet](https://steakwallet.fi) already supports WC2 for EVM chains, Solana and Cosmos SDK networks, we'd love to add NEAR support too.

We wrote the [Solana JSON-RPC specification](https://docs.walletconnect.com/2.0/json-rpc/solana), NEAR needs one too and we'd love to collaborate. 

@lewis-sqa I couldn't find any contact details but could you DM me on Twitter @0xAlex_ or pop into our [Discord](https://discord.gg/rqt4Cfnmh5)?

**Comment by lewis-sqa** [comment]
@AlexBHarley thanks for raising this issue and we truly apologise for the delayed reply!

There's been a lot of communication internally with NEAR to come up with an approach that we feel compliments both WalletConnect and the core concepts of NEAR's blockchain. Our first draft has recently been submitted to the NEP repo for a full review before we take steps to update the relevant repos for WalletConnect and Wallet Selector: https://github.com/near/NEPs/pull/368. Feedback is greatly appreciated! 🙂

**Comment by AmmarHumackicSQA** [comment]
Hi @AlexBHarley , I will close this issue for now, and for any other inquiries, please be free to reach out to us. Thanks!
