### ISSUE TITLE
Generate Sourcemap Error

### ISSUE THREAD

**Issue by keeplearning-near** [near/wallet-selector#279]
When trying to use wallet-selector, I found the following error on the console.
```
Failed to parse source map from 'filepath' file: Error: ENOENT: no such file or directory, open 'filepath'
```
version: 
@near-wallet-selector/core 3.0.2
@near-wallet-selector/near-wallet 3.0.2
@near-wallet-selector/sender 3.0.2

**Comment by lewis-sqa** [comment]
Hey @keeplearning-near, thanks for raising this issue!

Could I get some more details on your setup? What environment and bundler (if applicable) are you using?

My initial thought is this error is related to polyfills - potentially connected to `near-api-js` but I might be wrong

**Comment by lewis-sqa** [comment]
@keeplearning-near the bug repo was super helpful! It looks like it's an ongoing issue with CRA 5.x as discussed here: https://github.com/facebook/create-react-app/discussions/11767. I'm not entirely sure why it's trying to find the `.ts` source files when there's already source maps in our published packages - maybe there's a bug in `source-map-loader`?

This PR (referenced in the discussion above) tries to patch over the issue for now: https://github.com/facebook/create-react-app/pull/11752. I don't think this is a bug with our library unless I'm misunderstanding something?
