### ISSUE TITLE
Allow to pass callbackUrl when signAndSendTransactions with Near Wallet connected

### ISSUE THREAD

**Issue by phucloc8697** [near/wallet-selector#290]
**Is your feature request related to a problem? Please describe.**
My application needs additional process after transactions was successful. Using wallet.near.testnet will redirect to other page rather than stay in, so I need a way to customize the callback url like near-api-js package. 

**Describe the solution you'd like**
Add code to receive parameter callbackUrl and pass to the return function in this file
https://github.com/near/wallet-selector/blob/19af6005890a026a478ab0d093fc6856d8183874/packages/near-wallet/src/lib/near-wallet.ts#L188

**Comment by lewis-sqa** [comment]
Hey @phucloc8697, thanks for opening this issue!

My initial thoughts on a solution is similar to how we've tackled `walletUrl` by defining a value during setup:

```ts
// Init
setupNearWallet({ callbackUrl: "..." });

// Usage (e.g. click handler)
await selector.signAndSendTransactions({ ... });
```

Would this solve the issue you're having?

**Comment by phucloc8697** [comment]
@lewis-sqa  Sadly it's not. I need to use different callbackUrl  based on transactions used in `signAndSendTransactions`. Ideally, I can pass callbackUrl as a parameter to `signAndSendTransactions`, or is there a way to update callbackUrl after the `setupNearWallet `?

**Comment by lewis-sqa** [comment]
Hey @phucloc8697, I've opened a couple of PRs (`main` -> `v3.x` & `dev` -> `v4.x`) to address this requirement. As you mentioned above, you'll have the ability to pass a `callbackUrl` for `signAndSendTransaction` and `signAndSendTransactions`.

Let me know what your thoughts are on the solution(s) 🙂

**Comment by Yammoe** [comment]
@lewis-sqa  The solutions work perfectly for my case. Looking forward to getting this PR on new version soon 👍

**Comment by lewis-sqa** [comment]
Hi @phucloc8697,

You can now find the changes from #292 in our latest release, `3.1.0` 👍
