### ISSUE TITLE
Use new indexer service for indexer related queries

### ISSUE THREAD

**Issue by esaminu** [near/wallet-selector#321]
**Describe the bug**
Hey guys! I notice that there is some usage of the wallet indexer service in the repo and it has not been updated to use the new wallet indexer service which has been separated out per near/near-wallet#2637. I believe the only affected query right now is `/publicKey/${publicKey}/accounts` which will affect querying for ledger accounts in this case. You can see the defaults for each environment (`mainnet`/`testnet`/`staging`) in near/near-wallet#2637 as the `INDEXER_SERVICE_URL` under `environmentDefaults` and the affected queries under [services/indexer.js](https://github.com/near/near-wallet/pull/2637/files#diff-bc526cde76a703db769a95c6dc4b13e6d1d13c775e68c3e020e16f960992e255)

**To Reproduce**
1. Try to connect a ledger wallet
2. You will see `Error: Failed to get account id from public key`

**Expected behavior**
I should be able to connect a ledger wallet

**Comment by lewis-sqa** [comment]
@esaminu thanks for raising this issue! We've since released [`4.1.0`](https://github.com/near/wallet-selector/releases/tag/v4.1.0) that includes this new service 🎉
