### ISSUE TITLE
Can't select account if multiple accounts exist on my Ledger

### ISSUE THREAD

**Issue by esaminu** [near/wallet-selector#322]
**Is your feature request related to a problem? Please describe.**
If I have multiple accounts on my ledger, I can't select which account I want to login with

**Describe the solution you'd like**
It would be great to see a list of accounts on the ledger and select which one I'd like to login with if more than one account is returned by the indexer service (`/publicKey/${publicKey}/accounts`)

**Comment by kujtimprenkuSQA** [comment]
Hey @esaminu for raising this enhancement. 
This will feature will be available in the next release.
Latest changes are in [dev](https://github.com/near/wallet-selector/tree/dev) branch, you can also have a look at the linked PR above.
