### ISSUE TITLE
Multi-type wallet using the injected interface

### ISSUE THREAD

**Issue by lostpebble** [near/wallet-selector#335]
Hi there,

We're currently working on a wallet project and we'd like to integrate with Wallet Selector.

Our wallet will be available as both an extension and as a browser-based wallet and we'd like to provide a unified interface for consumer dapps to integrate our wallet, using a Promise-based async interface, whether the extension is detected or not. When the extension is not detected, we'll open a popup and use `window.postMessage()` to communicate with the SDK and do wallet actions like signing etc. eventually returning the result as the resolution of a Promise, giving the same experience as one might expect from an extension-based solution- this prevents full page redirects and refreshes, and unifies the integration to a single interface.

Looking at Wallet Selector though, it seems we have a choice between `BrowserWallet` or `InjectedWallet` types, and these seem to target quite specific use-cases of wallets that either implement full page redirects or Promised-based results, respectively.

In our case, the interface we'd be looking for would be the `InjectedWallet` interface in all cases, even when we'll be technically redirecting the user to a popup of our browser-based wallet. Would this be a valid usage of Wallet Selector? Currently it expects us to provide a `downloadUrl` but that shouldn't be necessary as we'll always have a fallback in the browser-based wallet. But anyway, since the wallet will always be seen as "installed"- it shouldn't be put into use.

**Comment by kujtimprenkuSQA** [comment]
Hey @lostpebble thanks for raising this issue.

Do you have any sort of preview of these wallets so we can have a bit more context on them?

Currently we do not see any problem using the same `InjectedWallet` interface  for both wallets based on the info provided.
We can modify the type for `downloadUrl` to `string | null` so it shouldn't be an issue if there's no available `downloadUrl`.

**Comment by kujtimprenkuSQA** [comment]
Hey @lostpebble ,

The process of integrating a new wallet in `Wallet Selector` can be done first by following this guide: [Custom Wallet Guide](https://github.com/near/wallet-selector/blob/main/packages/core/docs/guides/custom-wallets.md) .

So you would be creating a new package under `packages` which contains the necessary code for your wallet it's best to try and stay consistent with the other wallets we already have.

Then whenever you feel that you're ready just open a PR in our [dev](https://github.com/near/wallet-selector/tree/dev) branch and we will review it.

I understand it's still a pre-alpha version but whenever you have docs ready that explain how we can comunicate with your wallet(s), it would be nice if you could share them with us.

**Comment by lostpebble** [comment]
Thanks for the guidance! Will be sure to follow those steps when the time comes to integrate directly.

> I understand it's still a pre-alpha version but whenever you have docs ready that explain how we can comunicate with your wallet(s), it would be nice if you could share them with us.

Sure thing- currently its looking like we'll be sharing an NPM module as an "SDK" which dapps can use to integrate directly (or if they are using wallet selector, they'd use the wallet-selector package which underneath will use our SDK as well). This SDK will take care of detecting our extension and calling methods on the `window` object (similar to Sender), or otherwise falling back to using a popup method to our web wallet. In either case, it returns async promises with action results, in a simple unified interface (pretty much the same interface expected for `InjectedWallet`).

We will share documentation on our site about integration as soon as we have completed and tested the SDK.

**Comment by lostpebble** [comment]
Hi guys, I've finally finished the integration as described in this issue. Everything seems to work well. I've added documentation to our SDK here: https://sdk-reference.meteorwallet.app/classes/MeteorWallet

I've added a PR with the integration: https://github.com/near/wallet-selector/pull/348. Would really appreciate a review to check if everything is up to scratch :)

**Comment by AmmarHumackicSQA** [comment]
Hi @lostpebble , 

Thank you for your efforts! I will close the issue as the referenced PR #348 had been reviewed and merged.
