### ISSUE TITLE
Feedback from adopting wallet-selector

### ISSUE THREAD

**Issue by hcho112** [near/wallet-selector#349]
Hello,

I have been working on integrating the `wallet-selector` to [multisafe](https://github.com/near/ui.multisafe/pull/134) dApp and I would like to share my experience/struggles with the community and hoping that it will save some time for other devs who will be introducing `wallet-selector` to their dApp.

In general, `wallet-selector` is a great way to interact with NEAR blockchain and I do believe that NEAR community should really consider integrating `wallet-selector` soon. (Earlier the better) I was able to migrate the most of the transaction related code, utilising the benefit of unified `signAndSendTransaction` call. 

There are two main issues during the migration that I would like to share with the community. (This will be applicable to devs who already owns dApp and wanting to migrate `wallet-selector` to their dApp)

### **Issue 1.** Error on `Class Action is missing in schema: actions.actions`

I encountered this error when I was working on migrating existing code to be replaced with `signAndSendTransaction` from `wallet-selector`. After some research, I found that someone already had this [issue](https://stackoverflow.com/questions/68799878/receiving-error-class-action-is-missing-in-schema-actions-actions). Further investigation showed that `ui.multisafe` repo contained it's own version of `near-api-js` as `0.42.0` and it did affect on use of `signAndSendTransaction` from `wallet-selector`.

Eventually I resolved this issue by upgrading `near-api-js` from `ui.multisafe` to `0.44.2`. (My guess is that it has been fixed from `near-api-js` on https://github.com/near/near-api-js/commit/28c8941d2cc182b97728492029d6d719461183ca which is released at `0.43.0`)

**Acceptance criteria**
To help the migration better for devs in the future, would be ideal to setup a Peer Dependencies on `wallet-selector` to `near-api-js` with greater/equal to `0.44.2`. 

### **Issue 2.** Error on `Device is already open`

I encounter this issue when I was working on integrating `ledger wallet` from `wallet-selector` to `ui.multisafe`. Initially I did not touch any existing ledger related code on `ui.multisafe` and was planning to do a ledger wallet specific code migration in a different PR later. But when I  tried to select `ledger-wallet` from wallet-selector, app breaks with above error message.

The issue was that `ui.multisafe` is using `@ledgerhq/hw-transport-webhid` to create ledger instance which was conflicting with ledger instance from `wallet-selector`. I resolved the issue by do a full migration on ledger related codebase from `ui.multisafe` upfront and no longer using `@ledgerhq/hw-transport-webhid` instance.

**Acceptance criteria**
If there will be a migration guidance doc to help other devs to use `wallet-selector` and migrate their existing code, worth noting it down there so that this error can happen due to having two ledger instance. 

Hope this helps other devs in the future.

**Comment by AmmarHumackicSQA** [comment]
Hey @hcho112, 

Thanks for your detailed feedback! We worked on addressing the mentioned issues:

Issue 1: #353 

Issue 2: #360 

Feel free to post regarding anything else that we can work on improving. I will close this issue now and thank you again for your time and feedback.
