### ISSUE TITLE
Unable to redirect back to dApp after importing account (mainnet) | MyNearWallet

### ISSUE THREAD

**Issue by skiran017** [near/wallet-selector#350]
I trying to connect to my dApp on mainnet using MyNearWallet from the wallet modal. After I import or create account the page remains at the wallet page, does not redirect back to dApp or no connecting request is suggested. Where as if i change the contract id and network to testnet it works fine.

Steps to reproduce:

- Pull the repo and install dependencies by running ```yarn install```
- run ```yarn dev``` to start the server 
- Click on Login button and select MyNearWallet from the modal
- create or import an account on mainnet
It will observed that we are still on wallet page no redirection happened to the dApp.

What I have tried?
To get the latest version of wallet selector. I have also tested this with wallet-selector v4.0.0, this issue is there too

Sample repo :
https://github.com/skiran017/near-wallet-selector

Stack: NextJS
Browser: Chrome/Edge/FireFox

It would be really helpful to get a lead on how to fix this issue.

**Comment by lewis-sqa** [comment]
@skiran017 Thanks for raising this issue!

Have you tried testing this with MyNearWallet directly without Wallet Selector? It's confusing to me why it only works with `testnet` and not `mainnet`. I wonder if there's a bug on their end as changeing the network in Wallet Selector only modifies the `walletUrl` IIRC

**Comment by skiran017** [comment]
Thank you for the suggestion, i will reach out to MyNearWallet team and take their opinion. I dont think its anything to do with blacklisting as the app is deployed on production and gives the same issue.

**Comment by lewis-sqa** [comment]
@skiran017 No problem. If you find this is an bug with Wallet Selector, please feel free to reopen this issue and we can discuss a solution 👍

**Comment by skiran017** [comment]
Hello @kujtimprenkuSQA  @lewis-sqa,
I have reach out to MyNearWallet team requesting to look into this issue, they reverted back saying they fixed it and need to update the package from your end. Can you please look into this.
Thank you.

**Comment by AmmarHumackicSQA** [comment]
Hi @skiran017, I will reopen this issue and the team will take a look at it as soon as possible. Thanks!

**Comment by kujtimprenkuSQA** [comment]
Hey @skiran017 I think the issue can be here in this line:
https://github.com/near/wallet-selector/blob/main/packages/my-near-wallet/src/lib/my-near-wallet.ts#L39

We have already made changes in `dev` branch they will be updated on the next release.
https://github.com/near/wallet-selector/blob/dev/packages/my-near-wallet/src/lib/my-near-wallet.ts#L40

Have you tried passing a custom walletUrl when you call `setupMyNearWallet({walletUrl: "https://app.mynearwallet.com" })`, until we make the release?

**Comment by followdarko** [comment]
Hey, MyNearWallet team is here. This bug was fixed a month ago https://github.com/near/wallet-selector/pull/346. Sorry for rushing you, but when it will be released?

**Comment by skiran017** [comment]
Tested the connection working great, will keep testing more and get back to you if anything. Thank you for the hot fix.

**Comment by kujtimprenkuSQA** [comment]
The release has been made in NPM too, glad to hear everything is working now.
