### ISSUE TITLE
Ledger Support on Firefox browser

### ISSUE THREAD

**Issue by hcho112** [near/wallet-selector#361]
**Is your feature request related to a problem? Please describe.**
During the testing, we discovered that ledger does not show up on Firefox browser.

**Describe the solution you'd like**
Support ledger on Firefox browser

**Describe alternatives you've considered**
For every wallet type integrated, if it has special condition not to support certain browser, notify on terminal as warning so developers are aware which browser isn't supported.  

**Acceptance criteria**
Support Ledger on Firefox browser

**Additional context**
Chrome:
![image](https://user-images.githubusercontent.com/6027014/180320257-b084f392-8338-45a8-b65a-5bca1fe693d6.png)

Firefox:
![image](https://user-images.githubusercontent.com/6027014/180320313-8e4845d0-4b7a-4c2c-9c50-29bf50277fae.png)

**Comment by AmmarHumackicSQA** [comment]
I will close this issue now, but feel free to reopen it if there are some other suggestions that you might have. Thanks @hcho112
