### ISSUE TITLE
Model not opening when using Next.js

### ISSUE THREAD

**Issue by seaver-choy** [near/wallet-selector#368]
**Describe the bug**
Modal not opening when using Next.JS

**To Reproduce**
1. Implement example of React
2. Run on next.js typescript
3. modal.show() does nothing

**Expected behavior**
Expected is it runs on local and modal still pops up

**Device (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version 1.38.119 Chromium: 101.0.4951.67 (Official Build) (arm64)
- Next.js 10.2.3

**Comment by kujtimprenkuSQA** [comment]
Hey, @seaver-choy thanks for raising this issue.

Can you please share the project or reproduce the bug you're facing?

In the `dev` branch we have recently converted from `React` to `Next.js` to show that this project works just fine with both frameworks.
We still kept the name `react` on the folder but it's essentially a `Next.js` project: 
https://github.com/near/wallet-selector/tree/dev/examples/react

And here's another project that showcases that Wallet Selector packages work on `Next.js`:
https://github.com/kujtimprenkuSQA/guest-book-nextjs

If you're still having issues feel free to ask for help.

**Comment by AmmarHumackicSQA** [comment]
I will close this issue for now but feel free to reopen it if you are still having some issues. Thanks @seaver-choy
