### ISSUE TITLE
Confusion between react example vs what user actually see

### ISSUE THREAD

**Issue by hcho112** [near/wallet-selector#375]
**Describe the bug** There are some difference between what react example shows vs what users will see when they import `wallet-selector` into their project. In general, when a user decided to integrate `wallet-selector`, first thing they would do is to go through documentation and check/play with what is on `example`.

As an engineer who was working on integrating `wallet-selector` to `ui.multisafe` I confused many times, why things were working fine on `examples/react` and not working when I import `wallet-selector` and use them almost identical to what's on example. (For the details check [here](https://github.com/near/wallet-selector/issues/374))

With spending some time debugging with multiple issues, I found out that the main branch is not equal to release branch. Which is fine and normal, but as an end user, when I see the executable example, I would assume that it is what I will be getting when I import them into my project. However, `examples/react` reference to the latest state of the codebase not what user will be getting at latest release version.

My advice is that:

1.  Examples on `wallet-selector` repo should point to latest release version, so outcome of example is what user will be getting when they import `wallet-selector` into their project. (Deterministic!)
2.  Should conduct a smoke post deployment test (releasing new npm package) outside of wallet-selector package where import package like as if user would do
3.  Update/create readme (or alike) that briefly describes branching/releasing strategy and letting user know that main !== release branch.

**Comment by kujtimprenkuSQA** [comment]
Hey, @hcho112 thank you for raising this issue.

The main branch is equal to the release `v5.0.1` the only difference might be this PR https://github.com/near/wallet-selector/pull/366 about some improvements to docs so everything that is on main branch is included in the release.

To avoid confusion in the future we can have a readme as you suggested and explain what's the purpose of `main` and `dev` branch.

**Comment by kujtimprenkuSQA** [comment]
Regarding the advice mentioned in the issue:

1. `main` branch will be always equal to the latest release because we do not push to `mian` unless it's for a release.
2. In the future we plan to update the official [guest-book](https://github.com/near-examples/guest-book) example to integrate with `wallet-selector`.
3. This has been addressed on the linked PR above.
