### ISSUE TITLE
Risk of a failed connection with Near Wallet and My Near Wallet

### ISSUE THREAD

**Issue by max-mainnet** [near/wallet-selector#378]
**Describe the bug** [completeSignInWithAccessKey mechanism](https://github.com/near/near-api-js/blob/3ba842368e2e942a2d694d8eaa9ab68d640fabee/packages/near-api-js/src/wallet-account.ts#L221-L244) As a mechanism on near-api-js for a completeSignInWithAccessKey, it will delete search params from near wallet or my near wallet. We couldn't ensure just one walletConnection instance generated on first website rendering, if another walletConnection instance created and triggers above completeSignInWithAccessKey mechanism first, then account_id in the search params deleted, leading to a failure on completeSignInWithAccessKey in WalletConnection instance generated later by wallet-selector itself.

**To Reproduce**

1.  create a walletConnection instance outside WalletSelectorContextProvider.
2.  try to connect to near wallet or my near wallet by wallet-selector

**Comment by kujtimprenkuSQA** [comment]
Hey, @max-mainnet thank you for raising this issue.

I have double-checked the way we connect to both **Near Wallet** and **MyNearWallet** and we are doing it the way it's explained in the docs of `near-api-js`. 

After some more investigation and trying to understand why would one encounter this kind of issue I find it odd that you need to do a WalletConnection with (My) Near Wallet in your dApp before an end user has even chosen any of the wallets in the `Wallet Selector`.

In my opinion and from what I have seen in different NEAR examples and dApps there's always only one wallet connection.

**Is having multiple wallet connections in your dApp necessary?**
**I remember you mentioned that you added a workaround in your dApp for this issue would you mind sharing it with us?**

Looking at the method above and the constructor of WalletConnection class every time you do a `new WalletConnection()` and this [check ](https://github.com/near/near-api-js/blob/3ba842368e2e942a2d694d8eaa9ab68d640fabee/packages/near-api-js/src/wallet-account.ts#L113)returns false  the `_completeSignInWithAccessKey` is always called and it's not something we can prevent inside `Wallet Selector`

**Comment by max-mainnet** [comment]
> Hey, @max-mainnet thank you for raising this issue.
> 
> I have double-checked the way we connect to both **Near Wallet** and **MyNearWallet** and we are doing it the way it's explained in the docs of `near-api-js`.
> 
> After some more investigation and trying to understand why would one encounter this kind of issue I find it odd that you need to do a WalletConnection with (My) Near Wallet in your dApp before an end user has even chosen any of the wallets in the `Wallet Selector`.
> 
> In my opinion and from what I have seen in different NEAR examples and dApps there's always only one wallet connection.
> 
> **Is having multiple wallet connections in your dApp necessary?** **I remember you mentioned that you added a workaround in your dApp for this issue would you mind sharing it with us?**
> 
> Looking at the method above and the constructor of WalletConnection class every time you do a `new WalletConnection()` and this [check ](https://github.com/near/near-api-js/blob/3ba842368e2e942a2d694d8eaa9ab68d640fabee/packages/near-api-js/src/wallet-account.ts#L113)returns false the `_completeSignInWithAccessKey` is always called and it's not something we can prevent inside `Wallet Selector`

**Comment by max-mainnet** [comment]
> Hey, @max-mainnet thank you for raising this issue.
> 
> I have double-checked the way we connect to both **Near Wallet** and **MyNearWallet** and we are doing it the way it's explained in the docs of `near-api-js`.
> 
> After some more investigation and trying to understand why would one encounter this kind of issue I find it odd that you need to do a WalletConnection with (My) Near Wallet in your dApp before an end user has even chosen any of the wallets in the `Wallet Selector`.
> 
> In my opinion and from what I have seen in different NEAR examples and dApps there's always only one wallet connection.
> 
> **Is having multiple wallet connections in your dApp necessary?** **I remember you mentioned that you added a workaround in your dApp for this issue would you mind sharing it with us?**
> 
> Looking at the method above and the constructor of WalletConnection class every time you do a `new WalletConnection()` and this [check ](https://github.com/near/near-api-js/blob/3ba842368e2e942a2d694d8eaa9ab68d640fabee/packages/near-api-js/src/wallet-account.ts#L113)returns false the `_completeSignInWithAccessKey` is always called and it's not something we can prevent inside `Wallet Selector`

Hi @kujtimprenkuSQA , I would like to apologize around this issue, for it is not necessary to have multiple wallet connections. In my Dapp, I just to generate this wallet connection to view methods on contracts, in fact, I don't have to do this.

**Comment by max-mainnet** [comment]
Sure it is not able to prevent it inside wallet selector. I could just create Account class to view methods on contracts as well as other Dapps. Thanks for you time again !
