### ISSUE TITLE
Return if transaction did not include a deposit

### ISSUE THREAD

**Issue by mattlockyer** [near/wallet-selector#383]
**Description** If you examine the method `signAndSendTransaction` not (s), for my-near-wallet you will notice that there's this warning:

[https://github.com/near/wallet-selector/blob/56a391fa57513df3e7d952a4b0ae5cac81e97488/packages/my-near-wallet/src/lib/my-near-wallet.ts#L182-L185](https://github.com/near/wallet-selector/blob/56a391fa57513df3e7d952a4b0ae5cac81e97488/packages/my-near-wallet/src/lib/my-near-wallet.ts#L182-L185)

But no where in the method is a deposit checked. So transaction without deposits are returning undefined responses to the client.

**Acceptance Criteria**

*   [ ] check for deposit in actions
*   [ ] if there is no deposit, return the transaction result to the client

**Comment by kujtimprenkuSQA** [comment]
Hey, @mattlockyer thanks for raising this issue.

Looking at the source code of `near-api-js` the return type of `signAndSendTransaction` is `Promise<FinalExecutionOutcome>`:
https://github.com/near/near-api-js/blob/master/packages/near-api-js/src/account.ts#L208

So removing the `.then()` call would be the solution.

Tested it in our react example:
https://github.com/near/wallet-selector/blob/main/examples/react/src/components/Content.tsx#L119-L130

1. Transactions **without** deposit return the result of type `Promise<FinalExecutionOutcome>`.
2. Transactions **with** deposit redirect to MyNearWallet by default to approve or reject the transaction(s).
