### ISSUE TITLE
activating a node as a validator

### ISSUE THREAD

**Issue by AUXILIUM13** [near/wallet-selector#386]
At this stage, when copying the link, everyone presses CTRL + C, for this reason the link is no longer valid, because. "near login" process closes

1. enter the command in the terminal
2. then copy the link and paste into your browser
3. At this stage, when copying the link, everyone presses CTRL + C, for this reason the link is no longer valid, because. the "near login" process closes, for putty users:
you need to enter the command “near login” then click on the putty icon -> Copy All to Clipboard,
4. open notepad and paste the contents of the clipboard there, and copy the link from the notepad and open it in the browser
5. Grant access to Near CLI, click NEXT
6. further connect
7. Enter our account and click confirm
8. And after that we continue in the terminal:
9. Enter your account and press Enter
ten.

**Expected behavior**
when copying the link is valid

**Screenshots**
![1](https://user-images.githubusercontent.com/110920086/183695573-9d38921d-ea01-45b7-8af2-e86683a42fe9.png)
![2](https://user-images.githubusercontent.com/110920086/183695583-ba9a277c-fe05-474f-8d14-7577efe9f7be.jpg)
![2 jpg](https://user-images.githubusercontent.com/110920086/183695588-8706f44c-18dd-416c-a2fa-9bf5abed17ae.png)
![3](https://user-images.githubusercontent.com/110920086/183695594-383b5d29-0fdf-4b25-b6f4-5f2001bfeff9.png)
![4](https://user-images.githubusercontent.com/110920086/183695599-df74c4c9-b1b7-4ca6-8f25-2b4e412d1287.png)
![5](https://user-images.githubusercontent.com/110920086/183695604-cbda69be-3329-4e1c-b130-a65c940a8705.png)
![6](https://user-images.githubusercontent.com/110920086/183695611-ca233785-3fa6-475a-a262-2e29ee85d2b4.png)
![7](https://user-images.githubusercontent.com/110920086/183695616-74ff7637-ef3f-4a0d-8804-217b3c27c94a.png)

**Device (please complete the following information):**
 -windows 10
 -chrome

**Additional context**
At this stage, when copying the link, everyone presses CTRL + C, for this reason the link is no longer valid, because. "near login" process closes

**Comment by kujtimprenkuSQA** [comment]
Hey @AUXILIUM13 thanks for raising this issue.

It seems like you're having trouble with something related to `near-cli` and not with `wallet-selector`.

You will need to open an issue there: https://github.com/near/near-cli
