### ISSUE TITLE
Failed model initialization when one extension wallet removed when account is signed in on dApp

### ISSUE THREAD

**Issue by max-mainnet** [near/wallet-selector#388]
**Describe the bug** When the account is signed in on dApp side, then I remove the wallet I selected before (eg. math wallet), the I am to reload the page (that is to re-initialize the wallet selector modal), it throws an error.

I think it is due to [throw error on uninstalled wallet](https://github.com/near/wallet-selector/blob/92fc76e24464fa5aaa31589236f963b4b0cc9939/packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts#L227-L232). For one uninstalled wallet leads to all modules a failing initialization.

But what confused me is that it would not throw error when the account was not signed in.

**To Reproduce** Steps to reproduce the behavior:

1.  Go to [wallet selector example](https://near.github.io/wallet-selector/)
2.  Click on login, to select injected wallet (math wallet)
3.  to remove the wallet (math wallet)
4.  reload the page
5.  see the error
6.  add math wallet again.
7.  reload the page, and login out
8.  remove math wallet again, reload the page, no error appear

**Expected behavior** in a signed in state, after we remove out the extension, we hope that it behaves like not signed in state. We could clean up account state, the removed wallet could be seen in the modal and redirect to installing route once user click it .

**Comment by kujtimprenkuSQA** [comment]
Hey, @max-mainnet thank you for raising this bug.

We will fix this bug shortly and it will be part of the next release.
