### ISSUE TITLE
Output on myNearWallet signAndSendTransaction

### ISSUE THREAD

**Issue by Calcifer1001** [near/wallet-selector#399]
**Description**
When I call signAndSendTransaction logged with myNearWallet I get as an output an object of type Promise<void>. It would be nice to have some kind of object to be returned, either the object returned by the contract or the FinalExecutionOutcome object that corresponds to the transaction, in order to be able to show the user a message with the result of the transaction
**Acceptance Criteria**
Call a signAndSendTransaction with 0 deposit. For example, meta-v2.pool.testnet contract's method liquid_unstake doesn't accept deposit. This means, no redirection is made by myNearWallet.

**Comment by kujtimprenkuSQA** [comment]
Hey, @Calcifer1001 thank you for raising this issue.

Which version of `wallet-selector` are you using?

We've done some work on returning the result of transactions that don't have deposit for `MyNearWallet` in the last release `v5.0.3`: https://github.com/near/wallet-selector/pull/385

**Comment by Calcifer1001** [comment]
Upgraded core and my-near-wallet to 5.0.3 and worked. Thank you
