### ISSUE TITLE
Cannot build React example

### ISSUE THREAD

**Issue by billyzhang663** [near/wallet-selector#400]
I cannot build React example [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/21320283/184757688-fe084cb0-5b90-4120-be94-b7b4e5d3d19b.png)</span>](https://user-images.githubusercontent.com/21320283/184757688-fe084cb0-5b90-4120-be94-b7b4e5d3d19b.png) .

**Comment by kujtimprenkuSQA** [comment]
Hey, @billyzhang663 thank you for raising this issue.

It looks like you will need to build the `modal-ui` package, try one of these commands:

- `yarn build:all` (builds all packages)
- `yarn && yarn build:modal-ui && yarn build:all && yarn nx serve react` (installs dependencies, builds modal-ui, builds all packages, serves react example).

**Comment by billyzhang663** [comment]
It works!! Thanks for your quick help!
Btw, I faced another issue. how can I call walletConnection.account().viewFunction with this library?
How can I call a method of smart contract after signin?

**Comment by kujtimprenkuSQA** [comment]
Hey, we do not expose walletConnection in `wallet-selector` you can call methods of a smart contract via the JsonRpcProvider with `near-api-js`:

An example on how to call `getMessages` in `guest-book.testnet`:
https://github.com/near/wallet-selector/blob/main/examples/react/components/Content.tsx#L45-L58

**Comment by billyzhang663** [comment]
I am using that module.
```

export async function view(method, args){
  const { network } = window.selector.options;
  const provider = new providers.JsonRpcProvider({ url: network.nodeUrl });

  return await provider.query({
    request_type: "call_function",
    account_id: process.env.CONTRACT_NAME,
    method_name: method,
    args_base64: Buffer.from(JSON.stringify(args)).toString(),
    finality: "optimistic",
  }).then((res) => JSON.parse(Buffer.from(res.result).toString()));
}

await Wallet.view("method", {
        account_id: accountId,
        from_index: 0,
        limit: 10,
});
```

But it fails with this error:
`json-rpc-provider.js:329 Uncaught (in promise) Error: [-32700] Parse error: Failed parsing args: Invalid byte 125, offset 60.`

**Comment by kujtimprenkuSQA** [comment]
According to the documentation here: https://docs.near.org/api/rpc/contracts#call-a-contract-function
You need to encode the `args_base64` to "base64":

args_base64: Buffer.from(JSON.stringify(args)).toString("**base64**")

I can not reproduce your current error since I do not have info about the exact contractId and the method you're trying to call.

**Comment by kujtimprenkuSQA** [comment]
@billyzhang663 would it be possible for you to share a demo (github repo) where you reproduce the error you have encountered?

**Comment by AmmarHumackicSQA** [comment]
Hi @billyzhang663, I will close this issue as it has been [resolved](https://github.com/near/wallet-selector/issues/400#issuecomment-1216304133). Feel free to open a new issue if you are experiencing any other problems so we can try and help you. Thanks!
