### ISSUE TITLE
What is the reason of exposing only accountId, but not entire ConnectedWalletAccount?

### ISSUE THREAD

**Issue by karpovdmitryod** [near/wallet-selector#429]
During the migration to WalletSelector, we faced the fact that you are not exposing [ConnectedWalletAccount](https://near.github.io/near-api-js/classes/walletaccount.connectedwalletaccount.html) object.

Due to this, many functionalities available before switching to WalletSelected are no longer accessible.
e.g - you just recently added the possibility to get a user signature 
another example - we cannot create a new [Contract](https://near.github.io/near-api-js/classes/contract.contract-1.html) instance, and we are now rewriting everything to RPC calls.

What was the reason for not exposing this object to the end users?

**Comment by austinabell** [comment]
Curious about this too. Is the intended pattern that `Wallet` is used along with a signer account id string?

**Comment by grachyov** [comment]
Exposing `near-api-js` types would make it necessary to inject `near-api-js` or it's parts.

**Comment by karpovdmitryod** [comment]
> Exposing `near-api-js` types would make it necessary to inject `near-api-js` or it's parts.

but near-api-js already part of wallet selector dependencies.

**Comment by grachyov** [comment]
> but near-api-js are already part of wallet selector dependencies.
These are not directly available for wallet's injected scripts.

**Comment by amirsaran3** [comment]
@karpovdmitryod Not all wallets use the `ConnectedWalletAccount` interface. We only expose the `accountId` since all wallets expose at least that.

If you have any other questions feel free to reopen this issue.

**Comment by pharaouk** [comment]
No updates on this.....?
