### ISSUE TITLE
Unable to connect with WalletConnect

### ISSUE THREAD

**Issue by leomanza** [near/wallet-selector#442]
I need to integrate my dapp with **WalletConnect** using the wallet selector.
When I scan the QR code using **Trust Wallet** (Android and iOS devices), I get a message saying that it will take a few second to process, but after some minutes it does not connect.

I also tried with Math Wallet (Android app) and Onto Wallet.

Is there any working example that uses WalletConnect with NEAR wallet selector?

Here is a short video with the issue
https://www.loom.com/share/8f80467c54b141519164a73f26bb4632

Thanks

**Comment by kujtimprenkuSQA** [comment]
Hey, @leomanza thank you for raising this issue.

At the moment there is no official Wallet that supports WalletConnect + NEAR.
If you need to test WalletConnect with NEAR we already have an implementation in `near-wallet-selector/wallet-connect`

You may find this PR useful: https://github.com/near/wallet-selector/pull/441 in the description there's a link to NEPs PR in the description there it's explained how to test out WalletConnect + NEAR with Wallet Selector.

**Comment by leomanza** [comment]
Thanks @kujtimprenkuSQA!
Do you know if any wallet is planning to work on a NEAR provider for WalletConnect?
Thanks!

**Comment by AmmarHumackicSQA** [comment]
> Thanks @kujtimprenkuSQA! Do you know if any wallet is planning to work on a NEAR provider for WalletConnect? Thanks!

Hey @leomanza , we can share more info on that soon. It was planned to be worked on. We will keep you posted. 

I will close this issue for now. Thanks!
