### ISSUE TITLE
Multilanguage support for wallet selector Modal-UI

### ISSUE THREAD

**Issue by LuisDaniel2166** [near/wallet-selector#457]
Currently the language presented in the present modal for wallet selector is English, this is a limitation for people who use wallet selector and don't speak the language.

They could generate multilanguage support in the modal-ui to be able to approach more users within the different platforms.

Perhaps within the modal configuration or globally you could decide which language to display.

Add support for new languages like Spanish, French or others

**Comment by cloudmex-alan** [comment]
Team, we are asking for our spanish-oriented platform called nativonft.app, if you can add support to extra langs we can help you to translate this into spanish!

Spanish is a language with 550 million speakers!

You can reach me on TG if required help on this :) @alan_network

**Comment by AmmarHumackicSQA** [comment]
> Team, we are asking for our spanish-oriented platform called nativonft.app, if you can add support to extra langs we can help you to translate this into spanish!
> 
> Spanish is a language with 550 million speakers!
> 
> You can reach me on TG if required help on this :) @alan_network

Hi @cloudmex-alan we are currently working on this, and we will reach out regarding extra help. Thanks!

**Comment by DamirSQA** [comment]
We're in the final stage so I've reached out on Telegram regarding the help with Spanish translations.

**Comment by cloudmex-alan** [comment]
Thanks for the support team!
