### ISSUE TITLE
Signing in to multiple accounts

### ISSUE THREAD

**Issue by trezbouchez** [near/wallet-selector#461]
Is it possible to sign-in to more than one account? WalletSelectorState maintains an array of accounts but I haven't been able to sign-in to more than one at a time, at least not using Near Wallet. Calling signIn on an already-selected wallet does nothing (won't redirect to Near Wallet). The selector modal won't allow it either - it shows wallet as selected, clicking doesn't do anything.

**Comment by amirsaran3** [comment]
Hey @trezbouchez ,

Currently the only wallet options that allow you to connect with multiple accounts are Ledger and WalletConnect. 

We provided a `selector.setActiveAccount` which you can use to switch between accounts if you are connected with multiple.

**Comment by trezbouchez** [comment]
Thanks for explaining this, @amirsaran3. Correctly if I'm wrong: currently there's no way to tell whether the currently-used wallet supports multiple accounts (other than hard-coding). It'd be helpful for the front-end - actions like account switching, or signing-in to another account could be hidden when not applicable.

**Comment by amirsaran3** [comment]
@trezbouchez We provide a list of accounts (`selector.store.getState().accounts`). If there are more than one account you can show actions like account switching.

**Comment by AmmarHumackicSQA** [comment]
I will close this issue if there are no further questions. Feel free to reopen it if needed. Thanks @trezbouchez
