### ISSUE TITLE
Add a wallet

### ISSUE THREAD

**Issue by Calcifer1001** [near/wallet-selector#467]
I've cloned this repo, studied the package structure to add a new wallet to the wallet selector. I was able to make it work with the guestbook example, but I'm trying to integrate it with another dapp, getting errors.

I've never uploaded an npm package, so I'm not sure exactly how it's done, but I'm checking the resulting structure from adding the wallet-selector packages from npmjs and the one I'm leaving on the package folder and it's different. I'm assuming I'm missing some step.

Is it possible to get some assistance? Thank you

**Comment by kujtimprenkuSQA** [comment]
Hey, @Calcifer1001 thank you for raising this issue.

Can you please clarify what your goal is, do you want to add your wallet to Wallet Selector as a new package as it's done with other [packages](https://github.com/near/wallet-selector/tree/main/packages)?

If you wish to add it as other packages then you need to open a new PR that points to `dev` branch.

This guide might be helpful:
https://github.com/near/wallet-selector/blob/main/packages/core/docs/guides/custom-wallets.md

After PR is approved and merged we do the publishing to npm ourselves it would be something like this:
`@near-wallet-selector/your-wallet-name`

If I have misunderstood your question could you please provide us a demo so we can have a look at the errors you're seeing?

**Comment by Calcifer1001** [comment]
My goal is that. At that moment I already did most of the job and now I'm about to finish. 

Currently it works with the guestbook and one more app. The thing is that I started this about 2 months ago and had to do other things in the meantime, so it was slow. 

Just to be sure, what would be the next steps? For me to bring the latest changes from `dev` branch, make it stable and create a pull request?

Thank you!

**Comment by kujtimprenkuSQA** [comment]
Hey, the process to add a wallet into Wallet Selector is as mentioned above and can be done in these steps:

- Make sure it follows the security criteria detailed here https://github.com/near/wallet-selector/blob/main/CONTRIBUTING.md#listing-criteria-for-third-party-wallet-on-wallet-selector
- Add a new package with your wallet's name under /packages in this repo.
- Open a new PR against the `dev` branch.

After you submit a PR then we will review it. Currently, there are few similar PRs opened you might have a look at them here: https://github.com/near/wallet-selector/pulls

**Comment by Calcifer1001** [comment]
Thank you for your response.

I've just pulled the changes from dev, fixed the conflicts and tested it out, working fine. 

Also, I've just created the pull request. Hope it goes fine.

Thank you for your time!
