### ISSUE TITLE
BrowserWallet's should be enabled to optionally open in a new tab

### ISSUE THREAD

**Issue by jessupjn** [near/wallet-selector#488]
**Description**
`BrowserWallet` cause a full navigation away from the web page to login and to sign/send transactions. This causes a full refresh of the web app and often times a break in logic. It would be great to enable the option for `BrowserWallet` (maybe upon setup?) to open in a new tab / window instead of a full navigation away from the page - and hand back the result upon completion / termination. 

Related: https://github.com/near/near-api-js/issues/1010

**Acceptance Criteria**
Enable a flow for these wallets that doesnt involve a full navigation away from the client web app.

**Comment by kujtimprenkuSQA** [comment]
Hey, @jessupjn thank you for raising this issue.

Currently if not all most of the Wallets (especially browser wallets) use the default functionality of `near-api-js` .
By default when you call `walletConnection.requestSignIn(signInParams);` this method in `near-api-js` redirects you to the wallet URL.

In my opinion, the feature to optionally open the wallet on a new tab should be handled either by `near-api-js` or a wallet needs to extend the functionality of `near-api-js` to support it.

Wallet Selector can not add a custom way to `signIn`/`signAndSendTransaction(s)` to a wallet unless the wallet supports it.

One interesting approach to think about can be how `Meteor Wallet` handles the communication with the wallet: https://github.com/near/wallet-selector/tree/main/packages/meteor-wallet

**Comment by AmmarHumackicSQA** [comment]
Hey, @jessupjn I will close this issue for now, and you can reopen it if you have any additional questions. Thanks!
