### ISSUE TITLE
When wallet adapters throw, they should use consistent error codes.

### ISSUE THREAD

**Issue by jessupjn** [near/wallet-selector#495]
For example - it would be nice to know if `signAndSendTransactions` failed because the user rejected the request vs the transactions failing for any other number of reasons.

**Comment by DamirSQA** [comment]
Displayed are error messages retrieved from the wallets, but even if we do intercept them, we wouldn't be able to differentiate types for all of them and adapt accordingly.

**Comment by AmmarHumackicSQA** [comment]
Hey, @jessupjn I will close this issue for now but feel free to reopen it if you have any additional questions. Thanks for raising the issue!
