### ISSUE TITLE
Wallet-selector not working for local network

### ISSUE THREAD

**Issue by romanzac** [near/wallet-selector#504]
Is Wallet-selector designed to work with local dev (Kurtosis) environment ? If not, what is the alternative ?

<img width="753" alt="image" src="https://user-images.githubusercontent.com/28704247/195799373-46dacfa7-dcc8-4538-8338-d007c2407d01.png">

**Device:**
 - MacOS
 - Chrome

**Comment by kujtimprenkuSQA** [comment]
Hey, @romanzac thank you for raising this issue.

There's a little info provided here and not sure what the value of `this.network` is in your case.

Wallet Selector has presets only for `testnet` and `mainnet` it is explained in the docs here:
https://github.com/near/wallet-selector/tree/main/packages/core#options

Let's assume `this.network` in your project is equal to the string `local` if you use typescript in your projects you would get warnings before running your code, something like **TS2322: Type '"local"' is not assignable to type 'NetworkId | Network'.**

If you wish to use another network you will need to provide a custom config see the link above for more details.

It could be something like this:

```ts
const selector = await setupWalletSelector({
  network: {
    networkId: "local",
    nodeUrl: "https://your-custom-node-url",
    helperUrl: "https://your-custom-helper-url",
    explorerUrl: "https://your-custom-explorer-url",
    indexerUrl: "https://your-custom-indexer-url",
  },
  modules: [setupNearWallet({ walletUrl: "http:://127.0.0.1:8334" })],
});
```

**Comment by romanzac** [comment]
It worked for me nicely. Thanks a lot.
