### ISSUE TITLE
Passing `callbackUrl` when call  `signIn` function

### ISSUE THREAD

**Issue by irmannmal** [near/wallet-selector#517]
**Is your feature request related to a problem? Please describe.**
Our application need to customize callback url when call  `signIn` function

**Describe the solution you'd like**
Add code to receive parameter `callbackUrl` and pass to the return function in this file

https://github.com/near/wallet-selector/blob/8f73cb8a654d6767287cfc7a117c120233de2ee9/packages/core/src/lib/wallet/wallet.types.ts#L27

**Comment by amirsaranBIH** [comment]
@irmannmal Just to clarify the #518 PR. `successUrl` and `failureUrl` will only work for "browser" wallets like MyNearWallet and HERE Wallet.

**Comment by irmannmal** [comment]
How about wallet.near.org?

**Comment by irmannmal** [comment]
> > How about wallet.near.org?
> 
> Yes, NearWallet is basically the same as MyNearWallet.

Great, thank u for your response
