### ISSUE TITLE
NEAR/My NEAR wallet to use local private key to verify owner

### ISSUE THREAD

**Issue by tituszban** [near/wallet-selector#522]
**Description**

The NEAR web wallet stores the function access private keys it used to sign in, in local storage. Instead of having to go to a redirect, it would be much better, if it just used those, to sign the requested message.

If applicable add: Relates to #318 

**Acceptance Criteria**

Update the NEAR and My NEAR (and other web wallets where applicable) to use the local storage keys to sign a message.

Alternatively, allow `verifyOwner` to specify if a function access or full access key should sign the message, and only redirect to the wallet if full access keys were requested.

**Comment by amirsaran3** [comment]
@tituszban https://github.com/near/wallet-selector/pull/537 This PR will fix your issue.

**Comment by amirsaran3** [comment]
@tituszban The current implementation of `verifyOwner` in wallet-selector is not right. `verifyOwner` should be used before signing in without a wallet. We are working on a standard and implementation for this.

NEP: https://github.com/near/NEPs/pull/413

If you have other questions feel free to reopen this issue.
