### ISSUE TITLE
Here wallet connect issue

### ISSUE THREAD

**Issue by leomanza** [near/wallet-selector#530]
**Describe the bug**
Unable to connect with HERE wallet on testnet

**To Reproduce**
1. Go to wallet selector
2. Select Here Wallet
3. Scan QR code with mobile camera
4. No link or data found 

**Expected behavior**
User should confirm on Here wallet the dapp connection

**Screenshots**

![image](https://user-images.githubusercontent.com/6494202/197785584-0d513623-2be3-4461-b83f-c82a5826ad55.png)

**Device (please complete the following information):**
OS: IOS 15.6.1
Browser: Chrome

**Additional context**

**Comment by AmmarHumackicSQA** [comment]
Hey @leomanza , thanks for raising this issue! We tested it, and it was the same for us. We are getting this:

<img width="425" alt="Screenshot 2022-10-27 at 11 32 39" src="https://user-images.githubusercontent.com/95851006/198248740-27042a7e-c197-495f-841a-b452b94d03b8.png">

**Comment by AmmarHumackicSQA** [comment]
> Hey @leomanza , thanks for raising this issue! We tested it, and it was the same for us. We are getting this:
> 
> <img alt="Screenshot 2022-10-27 at 11 32 39" width="425" src="https://user-images.githubusercontent.com/95851006/198248740-27042a7e-c197-495f-841a-b452b94d03b8.png">

Can you guys @Neafiol @AZbang check this, thanks!

**Comment by AmmarHumackicSQA** [comment]
Hey @leomanza to update you that we reached out to the HERE Wallet team on their [Discord](https://discord.gg/hFZehuEa) regarding this issue, and it should be addressed soon. I will leave this open until it's resolved. Thanks!

**Comment by leomanza** [comment]
Thanks @AZbang and @AmmarHumackicSQA for taking a look at this issue.
