### ISSUE TITLE
`verifyOwner` does not work with NEAR Wallet

### ISSUE THREAD

**Issue by microchipgnu** [near/wallet-selector#531]
**Describe the bug**

I'm trying to sign a message with the `wallet-selector` and getting a 404 on the NEAR Wallet.

![Screen Shot 2022-10-27 at 11 56 07 AM](https://user-images.githubusercontent.com/5553483/198266636-1fde2a1b-1ba8-4725-b3f0-144f031f15a2.png)

**To Reproduce**

The implementation is simple. Make sure you connect with NEAR Wallet.

```ts

  const wallet = ... as Wallet

  const owner = await wallet.verifyOwner({
    message: message,
  }) as VerifiedOwner;


```

**Comment by kujtimprenkuSQA** [comment]
Hey, @microchipgnu thank you for raising this issue.

NEAR Wallet does not have support for `verifyOwner` and only a small number of wallets support it.

Wallets that support `verifyOwner`: MyNearWallet (testnet only), WalletConnect ([web-examples](https://github.com/WalletConnect/web-examples/pull/59) any network), MeteorWallet (any network).

**Comment by AmmarHumackicSQA** [comment]
> Hey, @microchipgnu thank you for raising this issue.
> 
> NEAR Wallet does not have support for `verifyOwner` and only a small number of wallets support it.
> 
> Wallets that support `verifyOwner`: MyNearWallet (testnet only), WalletConnect ([web-examples](https://github.com/WalletConnect/web-examples/pull/59) any network), MeteorWallet (any network).
> 
> NEAR Wallet will be deprecated in the future so not sure if they will add new features.

Hey @microchipgnu, I hope this information helped you, and if you have any other questions or issues feel free to reopen this one or raise a new one. Thanks!
