### ISSUE TITLE
Making the Modal UI Redirect Optional

### ISSUE THREAD

**Issue by gagdiez** [near/wallet-selector#532]
**Is your feature request related to a problem? Please describe.**
Currently, when selecting the wallet in the Modal UI the user gets redirected to the wallet automatically (at least in the case of WebWallets).

Being redirected automatically removes the capability of doing at least two things:

1. Some developers might just want to use the `verifyOwner()` feature of the wallet, for which it is not necessary to be first logged in.

2. At the same time, by not setting automatically the `accountId` of the wallet, one can easily create "template transactions" to use with different accounts. This is, one could use:

```js
wallet.signAndSendTransaction({
      signerId: "<this could be a variable>",
      receiverId: ...,
      actions: [ ... ],
});
```

This is helpful for projects that want to, for example, allow users to handle multiple accounts with NFTs. (note: this idea came from actual questions in the NEAR discord during office hours)

**Describe the solution you'd like**
It would be very nice to have an option in the modal UI that allowed us to immediately sign the user, or simply return the WalletConnector immediately.

**Describe alternatives you've considered**
Adding an `redirectToSignUser` flag in the `setupModal` arguments, which is `true` by default.

**Acceptance criteria**
The developer can select if a user should be redirected after selecting a wallet in the modal UI, or if only the wallet connector needs to be returned

**Comment by amirsaran3** [comment]
@gagdiez 

- From my understanding you don't want the user to be redirected when signing in using browser type wallets. This is not possible since the point of browser wallets is the redirecting to fetch the private key. We keep a function call access key in dApp storage so we can sign transactions without redirecting. Although this only works for transactions that only invoke the FunctionCall action. If your call has other actions like Transfer then you will have to be redirected to sign the transaction with other keys.
- In wallet selector there is a concept of multiple accounts. You can get list of accounts with `selector.store.getState().accounts` and switch between them with `selector.setActiveAccount()` so you can just provide the active account id to the `wallet.signAndSendTransaction` as the signerId.
- Regarding the `verifyOwner` we are creating an NEP standard for it so more information on it soon.

If this answer is not sufficient enough can you provide more information about this issue. Thank you.

**Comment by gutsyphilip** [comment]
@gagdiez You can reference the  draft for the `verifyOwner` NEP here:
https://github.com/near/NEPs/pull/413

**Comment by gagdiez** [comment]
@amirsaran3 thank you for the answer.

> This is not possible since the point of browser wallets is the redirecting to fetch the private key.

The redirection is not to fetch the private key (since the key stays in the `<wallet-url>.org` website), but to fetch the username (and potentially create a function access-key). Because of this, it is actually possible to create a "Wallet Connection" [without redirecting the user](https://docs.near.org/tools/near-api-js/wallet#wallet-connection). This gives a `WalletConnection` object that can be used to sign transactions (redirect the user to the web wallet, of course) or messages (once the NEP413 goes through).  

> In wallet selector there is a concept of multiple accounts
Could you share an example of login-in multiple accounts? 

If there is a simple way to login multiple accounts, then I would only require the modal UI to let me choose if I want to:
(1) sign-in the user (i.e. redirect it to fetch the username, with the option of creating an access-key in the process)
(2) directly ask the user to sign a message with one of their accounts

Since this would cover all the scenarios from my first comment.

P.S. If my point is still not clear, I would kindly ask you to give me until next week to create two examples to share with you.

Thank you for your time!

**Comment by amirsaran3** [comment]
@gagdiez Thanks for some clarifications.

Sorry, by fetch I meant to access/view private key so it can be used for signing. 

Some wallets in the wallet-selector can utilize the `signerId` param in `signAndSendTransaction`, but some don't. I think we can work on this so you can pass in the `signerId` for every wallet. Currently if you don't pass the `signerId` param the active signed in account id will be used.

Currently only WalletConnect and Ledger wallets can return more than one account when signing in. Others let you choose only one wallet at a time.

I would like to see the examples when you finish them. They would help a lot.

**Comment by AmmarHumackicSQA** [comment]
> @gagdiez Thanks for some clarifications.
> 
> Sorry, by fetch I meant to access/view private key so it can be used for signing.
> 
> Some wallets in the wallet-selector can utilize the `signerId` param in `signAndSendTransaction`, but some don't. E.g. If you are signed in with Sender and have two accounts on it (a.testnet and b.testnet). If you pass c.testnet as the `signerId` it will not be able to sign it since it doesn't have access keys for it. I'm not sure how this would work. Can you explain more about this.
> 
> Currently only WalletConnect and Ledger wallets can return more than one account when signing in. Others let you choose only one wallet at a time.
> 
> **I would like to see the examples when you finish them. They would help a lot.**

Hey @gagdiez , any news regarding these examples? If you maybe had time to work on them. Thanks!

**Comment by gagdiez** [comment]
I'll close this issue, if needed I'll open it again, thanks
