### ISSUE TITLE
Add opportunity to pass a callback after succes/unsecces authorization or add opportunity to subscrube on envent

### ISSUE THREAD

**Issue by ruziev-dev** [near/wallet-selector#533]
I need to run some logic after succesful auth with some wallet.
Or I need to notyfy user about failed auth.

If user choose MyNearWallet it works good since there is a full reload of page. But when user choose another wallet his application can be authorized but to understand it user have to reload page. So I offer to add opportunity to pass a callback after succes/unsecces authorization  (variant 1) or add opportunity to subscrube on envent (variant 2)

### Variant 1

```ts
this.walletSelector = await setupWalletSelector({
      network: this.network as NetworkId,
      modules: [ 
        // pass callback onAuthSucces/onAuthError to wallets modules               
        setupMyNearWallet(),
        setupLedger(),
        setupSender(),
        setupMeteorWallet(),
        setupMathWallet(),
      ],
```
### Variant 2: add events to subscribe

```ts
walletSelector.on("onAuthSucces", () => {})
walletSelector.on("onAuthFailed", () => {})
```

**Comment by amirsaran3** [comment]
@ruziev-dev https://github.com/near/wallet-selector/pull/536 will solve this issue you are having. It will probably be liv on next release in few week.
