### ISSUE TITLE
Verify-owner endpoint returning 404 error now on mynearwallet and testnet.wallet.near.org

### ISSUE THREAD

**Issue by june07** [near/wallet-selector#547]
Using the verify-owner endpoint returns a 404 error from the wallet redirect...

![image](https://user-images.githubusercontent.com/11353590/200366067-15ba08f8-7d3f-4954-8fe2-ce2b54956757.png)

**To Reproduce**
1. Use the `wallet.verifyOwner` method as per the API
2. See error

**Expected behavior**
There should be no 404 error.  It was working fine previously.

**Screenshots**
![image](https://user-images.githubusercontent.com/11353590/200366683-d6926029-f066-4fca-8731-3160bc4f0c0b.png)

**Device (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version Version 107.0.1418.35 (Official build) (64-bit)

**Comment by andy-haynes** [comment]
This functionality was disabled in the `mynearwallet/near-wallet` fork on October 27 (it has never been enabled on any `near.org` domain): https://github.com/mynearwallet/near-wallet/blob/master/packages/frontend/src/app/App.js#L113

When they roll back this change the endpoint will be available again.

**Comment by andy-haynes** [comment]
The MNW team is aware of the broken functionality and says they will have a solution "in the near future".
