### ISSUE TITLE
Support near-api-js ^1.1.0

### ISSUE THREAD

**Issue by felixniemeyer** [near/wallet-selector#571]
**Is your feature request related to a problem? Please describe.**
I get a build warning, because the near-api-js version I'm using which is a peer dependency of wallet-selector is too high: 
```
[2/2] Regenerating lockfile and installing missing dependencies...
warning " > @near-wallet-selector/core@7.2.0" has incorrect peer dependency "near-api-js@^0.44.2".
warning " > @near-wallet-selector/ledger@7.2.0" has incorrect peer dependency "near-api-js@^0.44.2".
warning "@near-wallet-selector/ledger > @near-wallet-selector/wallet-utils@7.2.0" has incorrect peer dependency "near-api-js@^0.44.2".
warning " > @near-wallet-selector/my-near-wallet@7.2.0" has incorrect peer dependency "near-api-js@^0.44.2".
``` 
I want to use a recent version of near-api-js and wallet-selector.

**Describe the solution you'd like**
I would like to be able to use near-api-js version ^1.1.0 along with wallet-selector.

**Acceptance criteria**
The packages core, ledger, wallet-utils and my-near-wallet need to work with version ^1.1.0 of near-api-js
```
...
 "peerDependencies": {
    "near-api-js": "^1.1.0"
  }
```

**Comment by kujtimprenkuSQA** [comment]
Hey, @felixniemeyer thank you for raising this issue.

You can install any version of near-api-js equal to or higher than `^0.44.2` the above log seems to be just a warning you can ignore it for now. We have been testing the wallet selector with the latest versions and it works just fine.

We will soon update the range of `near-api-js` in this project.

Will close the issue for now, feel free to open it if there are any errors with the version you're using.
