### ISSUE TITLE
Update NEAR API JS 1.1.0

### ISSUE THREAD

**Issue by gagdiez** [near/wallet-selector#577]
**Description**
`near-api-js` is in version 1.1.0, but `wallet-selector` still uses `0.44.X`.

**Acceptance Criteria**
The version of `near-api-js` in package.json is `1.1.0`

**Comment by kujtimprenkuSQA** [comment]
Hey, @gagdiez thank you for raising this issue.

This will be done in the next release, a PR ( https://github.com/near/wallet-selector/pull/576 ) was already made yesterday to address this issue.

Just to let you know `near-api-js` is just a peerDependency in the packages so dApps can install/use any version equal to or higher than `^0.44.2`.

There should be no issues if a dApp uses the latest version even now.
