### ISSUE TITLE
Connect into multiple wallets at the same time

### ISSUE THREAD

**Issue by poriyaalarsamvelraja** [near/wallet-selector#584]
Currently, when we wish to switch different wallet it signout the current wallet.  The requirement is to have multi-wallet connect like Zerion or Zapper in EVM chains.

**Comment by kujtimprenkuSQA** [comment]
Hey, thank you for raising this issue.

- As a user how does it make sense to be connected to multiple wallets at the same time, with which wallet are you interacting?
- Will the user be signed in to the same smart contract in these wallets?
- What is the benefit of being connected/signedIn in multiple wallets at the same time?

**Comment by AmmarHumackicSQA** [comment]
@poriyaalarsamvelraja gentle bump on this. If you can provide us with more details through answers to the questions @kujtimprenkuSQA posted. Thanks!

**Comment by AmmarHumackicSQA** [comment]
@poriyaalarsamvelraja I will close this issue for now. Feel free to reopen it if needed. Thanks!
