### ISSUE TITLE
Sender wallet not working properly

### ISSUE THREAD

**Issue by VlodkoMr** [near/wallet-selector#592]
**Describe the bug**
I try to use Sender wallet (with @near-wallet-selector/sender installed and configured) but it don't update web interface after connection (still show that user not authenticated). Maybe it require some additional settings or events, but I don't find solution in the documentation.

**To Reproduce**
I recorded the video to show this issue: https://youtu.be/b-b45JrGQ8M

**Device (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Wallet Selector version: 7.2.1

**Comment by kujtimprenkuSQA** [comment]
Hey, @VlodkoMr thank you for raising this issue.

Here are the docs about the list of events emitted by the wallet selector:
https://github.com/near/wallet-selector/blob/main/packages/core/docs/api/selector.md#onevent-callback

In the video shown above inside the modal it shows as "Connection Successful" so at this point you are connected and you should have an account:

```ts
const { accounts } = selector.store.getState();
console.log(accounts)
// [{ accountId: "chatme.near", active: true }]
```

Make sure you're updating the state in your dApp correctly, you can also have a look at our [examples](https://github.com/near/wallet-selector/tree/main/examples).

If you're still having trouble please share a demo with us where you can reproduce the issue you're having.

**Comment by AmmarHumackicSQA** [comment]
> Hey, @VlodkoMr thank you for raising this issue.
> 
> Here are the docs about the list of events emitted by the wallet selector: https://github.com/near/wallet-selector/blob/main/packages/core/docs/api/selector.md#onevent-callback
> 
> In the video shown above inside the modal it shows as "Connection Successful" so at this point you are connected and you should have an account:
> 
> ```ts
> const { accounts } = selector.store.getState();
> console.log(accounts)
> // [{ accountId: "chatme.near", active: true }]
> ```
> 
> Make sure you're updating the state in your dApp correctly, you can also have a look at our [examples](https://github.com/near/wallet-selector/tree/main/examples). Live example: https://near.github.io/wallet-selector/
> 
> If you're still having trouble please share a demo with us where you can reproduce the issue you're having.

Hey @VlodkoMr let us know if this helped you and if we can close this issue. Thanks!
