### ISSUE TITLE
React 18 repeated rendering when invoke `createRoot` function

### ISSUE THREAD

**Issue by SteveYuOWO** [near/wallet-selector#605]
### Description
The error occurs when using react 18

> react-dom.development.js:86 Warning: You are calling ReactDOMClient.createRoot() on a container that has already been passed to createRoot() before. Instead, call root.render() on the existing root instead if you want to update it.

I found a possible conflict between the modal-ui code and the react code. Repeated rendering issues.

https://github.com/near/wallet-selector/blob/main/packages/modal-ui/src/lib/modal.tsx#L20-L32
```
  const container = document.getElementById(MODAL_ELEMENT_ID);
  const root = createRoot(container!);

  const render = (visible = false) => {
    root.render(
      <Modal
        selector={selector}
        options={options}
        visible={visible}
        hide={() => render(false)}
      />
    );
  };
```
### Solution
One of the solution is to export the `Modal` and let the client insert to the code.
For previous user compatibility issues, we can use a `renderByModal: boolean` option.

**Comment by SteveYuOWO** [comment]
This is a warning, the reason for not showing modal-ui is because I didn't import the css.
`createRoot` twice will cause a warning but will not have serious consequences

**Comment by DamirSQA** [comment]
Fixed multiple modal containers being added to DOM. In regard to warning, it might be an issue with an NX setup, but it's getting displayed only during rebuild and it's not affecting anything.
