### ISSUE TITLE
Using mynearwallet for making a transaction after connecting wallet

### ISSUE THREAD

**Issue by sulaysumaria** [near/wallet-selector#618]
For MyNearWallet, user is redirected to the nearwallet app and then redirected back to my app. But doing so, the `wallet` object gets reset and I can no longer call the `callMethod` on the `wallet`.

I am following the tutorial here: https://docs.near.org/develop/integrate/frontend

When I try to call below, it results in error:

```js
await wallet.callMethod({ method: 'set_greeting', args: { greeting: greeting.value }, contractId: CONTRACT_ADDRESS });
```

The error says that `this.wallet` is not defined and thus cannot call `signAndSendTransaction`.

Is there any way to persist the `this.wallet` object or any way to re-load/re-populate the `this.wallet` without redirecting to near wallet?

**Comment by DamirSQA** [comment]
Hi @sulaysumaria , thanks for raising an issue. Upon initial investigating, it looks like there's no issues with wallet-selector.  
You can provide more details, and maybe capture the issue on video so we can confirm that.

**Comment by AmmarHumackicSQA** [comment]
@sulaysumaria I will close this issue for now. Feel free to reopen it if needed. Thank!
