### ISSUE TITLE
About when wallet is locked and on accounts switched from wallet

### ISSUE THREAD

**Issue by 99sudarshan** [near/wallet-selector#626]
**1. When account changed: Event triggering is not persistent for on('accountsChanged', ......)**

I have implemented like this when changing the account from wallet in my **walletSelectorContext.ts** but its didn't trigger on account changed even not rendered **walletSelectorContext.ts** whether its just logged from wallet selector maybe **store.ts** or **sender.ts**

```javascript useEffect(() => {
const subscription = selector?.on('accountsChanged', ({ walletId,accounts }) => {
console.log(account changed ${walletId})
})

return ()=>subscription?.remove()
}, [selector])

**Comment by 99sudarshan** [comment]
**2. When wallet is locked: Detect and request wallet unlock .**

I am facing this from sender wallet. when i unlocked the wallet its still catch error **"wallet is locked"** and I have implemented it like this and also dispatching some state statically to reload the page when user unlocked the wallet.

```javascript 
const handleConnectWallet: () => void = async () => {
try {
if (selector.isSignedIn()) {
const wallet = await selector.wallet()
// console.log("wallet",wallet)
// console.log("selector",selector)
const owner = await wallet.verifyOwner({
message: "Authorize this wallet to access your account"
})
if (owner) {
const response = await login(owner)
if (response?.status === 200) {
dispatch(changeSignState(true))
}
}
} else {
modal.show()
}
} catch (error) {
console.log(error)
dispatch(
toast.error({
message: t("unlock-wallet") || ""
})
)
dispatch(changeSignState(false))
setReload(true)
}
}

**Comment by amirsaran3** [comment]
1. The problem with Sender is that when you change accounts you are not signed in to the new one. That is something that they need to fix.
2. This is also something that Sender needs to fix

All they wallets are currently working on implementing the Injected Wallet NEP standard. This will help make everything consistent and working.

**Comment by AmmarHumackicSQA** [comment]
@99sudarshan I will close this issue for now. Feel free to reopen it if needed. Thanks!
