### ISSUE TITLE
Give dApps access to / control of public key

### ISSUE THREAD

**Issue by lostpebble** [near/wallet-selector#641]
One of the dApps who are attempting to integrate our wallet with the Wallet Selector is having issues because they need to have access to the connected Account's function access public key. We are going to provide an interface for them to obtain it (I guess the easiest is to probably query the RPC with `view_access_key_list` and search for the contract id)- but that starts to defeat the point of having a unified interface such as the Wallet Selector for dApps.

I'm not entirely sure why the ability to generate and pass your own public key inside `SignInParams` is not possible:

```ts
export interface SignInParams {
  contractId: string;
  methodNames?: Array<string>;
  publicKey?: string; // <- dApp optionally controls key
}
```

But even so, I think there should at least be a way to access the public key which was generated internally, using the Wallet Selector interface.

Currently, this is what `Account` looks like according to Wallet Selector:

```ts
export interface Account {
  accountId: string;
}
```

It might be useful to add another property there (can be optional) which can hold the contract's access `publicKey` string.

Or perhaps I'm mistaken and this is already possible. In that case, would love to see an example of it.

**Comment by amirsaran3** [comment]
https://github.com/near/wallet-selector/pull/653
