### ISSUE TITLE
Add wallet-connect desktop sign-in

### ISSUE THREAD

**Issue by xssmd5** [near/wallet-selector#656]
![image](https://user-images.githubusercontent.com/36746093/213694837-7d5a5226-498f-4caf-a4e6-ad92d0c002b4.png)

**Comment by DamirSQA** [comment]
Hi @xssmd5 , desktop tab is not enabled as listed wallets in official Wallet Connect dialogue are not supporting Near.

**Comment by xssmd5** [comment]
Hi @DamirSQA, fireblocks supports Near. 
https://www.fireblocks.com/blog/expanding-our-web3-connectivity-with-near-defi-and-dapps-support/

**Comment by paulmattei** [comment]
Also Opto wallet. https://optowallet.com/

**Comment by looter** [comment]
@DamirSQA FYI WalletConnect is chain agnostic and NEAR supports WalletConnect. Optos is a NEAR wallet that is also live on WalletConnect V2. I'd encourage the NEAR wallet-selector team reach out to me to discuss how to make sure NEAR WalletConnect compatibility is 100!

**Comment by DamirSQA** [comment]
Even if we show the desktop tab of the WalletConnect qr-modal, this will not guarantee that Fireblocks is supported by Wallet Selector.

There needs to be a new package under `packages/fireblocks-wallet` and this would ideally handle the communication between Wallet Selector and this Fireblocks Wallet.

Does Fireblocks have support for `@near-wallet-selector/wallet-connect?`

**Comment by xssmd5** [comment]
@DamirSQA FireBlocks is supported, I can connect to the Wallet Selector by scanning QR code.
Mobile app can be used but for desktop sign in need to show the desktop tab
