### ISSUE TITLE
Old instance of `onHide` callback invoked when Modal is closed

### ISSUE THREAD

**Issue by toteto** [near/wallet-selector#661]
**Describe the bug**
Old instance of `onHide` callback invoked when Modal is closed.

**To Reproduce**

1. Minimal reproduction code
```ts
import { setupModal } from '@near-wallet-selector/modal-ui';

const walletSelector = setupWalletSelector(...)

const modal1 = setupModal(walletSelector, { onHide: () => console.log('THIS IS MODAL 1') })
const modal2 = setupModal(walletSelector, { onHide: () => console.log('THIS IS MODAL 2') })

modal2.show();
```

2. Dismiss the dialog by clicking on 'X'
2. In the console there will be "THIS IS MODAL 1" printed

**Expected behavior**
Because the setup for `modal2` and `modal2.show` was invoked, it makes sense for: `THIS IS MODAL 2` to be printed.

**Additional context**

The `options.onHide` is not provided as dependency to the `handleDismissClick` (line 95)

https://github.com/near/wallet-selector/blob/cc521d2afbba36b6df723b4056925687b51fefec/packages/modal-ui/src/lib/components/Modal.tsx#L85-L98

Additionally to this, having statefull `setupModal` method makes it very easy for us developers to shoot ourself in the foot. I am not sure if the issue I am having affects the other aspects of the config of the modal.

**Comment by kujtimprenkuSQA** [comment]
Hey, @toteto thank you for raising this issue.

The `modal` works in a Singleton pattern this would mean once you call `setupModal` in your dApp it will run the logic for setting up the modal but if you call `setupModal` again it will return the same instance every time so in your example code `modal2` is just pointing to the reference of `modal1` if that makes sense.

**Comment by toteto** [comment]
Hey @kujtimprenkuSQA, looking at the singleton implementation on https://github.com/near/wallet-selector/blob/cc521d2afbba36b6df723b4056925687b51fefec/packages/modal-ui/src/lib/modal.tsx, it doesn't look that is full singleton. There is computation and logic being performed (example: `const root = createRoot(container!);`) and there is new render function created.  

If I knew that the modal is singleton, the would be different design proposal for https://github.com/near/wallet-selector/issues/633

An example of what would work better would be to provide the callback via the `modal.show(onHide)` or as a event listener on `modal.on('onHide', () => {... )`.

Can you let me know if you are willing to change where the callback is being provided?

**Comment by kujtimprenkuSQA** [comment]
Hey, @toteto thank you for your feedback.

You're right there's some extra logic on the setupModal I only meant to say that `modal1 === modal2` would return true.
>An example of what would work better would be to provide the callback via the modal.show(onHide) or as a event listener on modal.on('onHide', () => {... ).

In the #633 issue, I initially thought that the suggested approach would work best for you since you.

In my opinion, the best solution would be for us to have an `EventEmitterService` internally and in the `modal` instance to expose .`on(event, callback)` and `.off(event, callback)` callbacks. This would align with the core package on how we do it for the `selector`. 

So developers can listen and remove these event listeners the same way it's described here:
https://github.com/near/wallet-selector/blob/main/packages/core/docs/api/selector.md#onevent-callback

Would this work better in your case?

**Comment by toteto** [comment]
Thanks @kujtimprenkuSQA for the fast response! Yes, the proposal with the `EventEmitterService` would work for my and probably other's usecases better then the current approach.

**Comment by kujtimprenkuSQA** [comment]
Hey, @toteto this PR #671 is adding support for listening to modal events like `.on(event, callback)`.

Right now I added am emitting the event only for `user-triggered` reason.

The only other case when we close the modal is when users get signed-in successfully, should we emit the `onHide` event with  `wallet-navigation` reason in this case?

**Comment by toteto** [comment]
#671 looks good from my side

Think it is good idea to have also the event emitted in other cases since it is good idea for the application to know. Currently my app doesn't need to know when the dialog hides for reason of `wallet-navigation` because it listens for the `wallet-selector` `signedIn` events. But, I can imagine when this can be useful. 

Thanks a lot for the fast issue resolution!

**Comment by kujtimprenkuSQA** [comment]
The #671 PR has been merged and the fix will be live in the next release, we do not have a set date for the next release, we will let you know as soon as we have more info.

**Comment by kujtimprenkuSQA** [comment]
@toteto we have made a new release please check if the issue has been resolved.
