### ISSUE TITLE
Failure to connect to NearWallet and MyNearWallet `Failed to sign in with MyNearWallet: null has no properties`

### ISSUE THREAD

**Issue by toteto** [near/wallet-selector#670]
**Describe the bug**

Since the addition of `Account.publicKey` in v7.6.1 by https://github.com/near/wallet-selector/pull/653 there has been a bug that prevents DApps without signer (Full Access or Function Call keys) to connect properly. 

**To Reproduce**
1. Setup the `walletSelector` with MyNearWallet
2. Setup the modal with `methodNames: []` and `contractId: ''`
3. Show the modal and go through the connection process
4. Upon return, run the `walletSelector` setup to consume the URL query parameters. 
5. The sign in to the wallet is not successful and no transactions can be signed

**Expected behavior**
The sign in to the wallet is successful with `Account.publicKey` being `undefined`. Transactions are signed by the wallet.

**Screenshots**

![image](https://user-images.githubusercontent.com/1628876/215593705-7b01315a-ec6d-464b-942c-05abfbdee16c.png)

**Additional context**

- Slightly related to https://github.com/near/wallet-selector/issues/669
- If the call to get the `publicKey` is made considering the `signer.getPublicKey` might be undefined/null, it will probably work as expected

```
publicKey: (
          await _state.wallet.near.signer?.getPublicKey(
            accountId,
            options.network.networkId
          )
        )?.toString()
```

**Comment by kujtimprenkuSQA** [comment]
Hey, @toteto we have just published a new version`v7.8.1` the errors about getting the publicKey with (My)NearWallet should not show.
