### ISSUE TITLE
Consider contract and methods parameters as a condition of staying logged in.

### ISSUE THREAD

**Issue by max-mainnet** [near/wallet-selector#690]
**Is your feature request related to a problem? Please describe.**
If the dApp wants to change the sign in contractId or its methods in its new version, the selector instance still keeps the previous state like accounts, contract, method. 

Specifically, the user is signed in at dApp by selector, then the dApp want to change from contract-a.near to contract-b.near to use functioncall keys of contract-b.near, still on user side, if he does not sign out and sign in again, he can not do function call at contract-b.near  for the selector doesn't have the functioncall key of the new one . 

**Describe the solution you'd like**
As the title shows, would it be possible to validate the methods and contractId between passed ones and kept ones ?  If the kept contract is not the same as passed contractId, we are to sign out  the wallet ? Then, need to sign in with new contractId and add functioncall key for it.

**Comment by AmmarHumackicSQA** [comment]
@max-mainnet I will close this issue as per our discussion on Discord. If you want to leave some comments here for a future reference feel free to do so. Thanks!
