### ISSUE TITLE
wallect-connect sign-in without creating keyPairs

### ISSUE THREAD

**Issue by xssmd5** [near/wallet-selector#691]

**Comment by DamirSQA** [comment]
Hi @xssmd5 , In this moment Wallet Connect is aligned with [InjectedWallets NEP ](https://github.com/near/NEPs/blob/master/specs/Standards/Wallets/InjectedWallets.md), therefore FunctonCall is required to sign in. 
Suggested enhancement might be become available after [NEP 0413: Add signMessage method to Wallet Standard](https://github.com/near/NEPs/pull/413) is introduced.

**Comment by AmmarHumackicSQA** [comment]
Hi @xssmd5 do you have any additional questions regarding this or we can close the issue? Thanks!
