### ISSUE TITLE
No Transaction hash returned from signing transaction on XDefi wallet

### ISSUE THREAD

**Issue by Ebube111** [near/wallet-selector#699]
**Describe the bug**
No Transaction hash returned from signing transaction on XDefi wallet and also no returned error even when i wrap in a try catch block

**To Reproduce**

**Expected behavior**
I am supposed to get an object that contains the transaction hash or something similar like signing transactions with other wallets but nothing is returned, i followed the Xdefi docs on near contract and the method - `signAndSendTransaction`

**Screenshots**
![Here is the code](https://user-images.githubusercontent.com/46991166/218124833-c0848c12-2872-4dc5-8d49-8891d8064763.png)

**Device (please complete the following information):**

**Additional context**

**Comment by kujtimprenkuSQA** [comment]
Hey, @Ebube111 thank you for raising this issue.

You are right and this seems to be an issue only with the XDEFI Wallet it ideally should return a response of type `FinalExecutionOutcome`:
https://github.com/near/near-api-js/blob/master/packages/near-api-js/src/providers/provider.ts#L85

XDEFI Transaction response

![xdefi-transaction](https://user-images.githubusercontent.com/95851345/218500049-5e926672-4d14-4f91-9fc5-21e1fd3b625d.png)

Sender transaction response:

![sender-transaction](https://user-images.githubusercontent.com/95851345/218500012-4cf0dda3-5c4c-4b7a-a8c2-ab3c7aaed125.png)

We will let the XDEFI Wallet team know about this issue.

**Comment by hinterlist** [comment]
Hey @Ebube111 , thank you for reporting. Just want to let you know that I was able to replicate issue and already working on fix, will keep you updated.

**Comment by hinterlist** [comment]
We will push hotfix today

**Comment by AmmarHumackicSQA** [comment]
@Ebube111 Thanks for raising the issue! The reported has been fixed with the latest version, and this issue can be closed now.
