### ISSUE TITLE
Allow Manual Trigger of `onWalletSignedIn()` From Within Module

### ISSUE THREAD

**Issue by BenKurrek** [near/wallet-selector#703]
**Description**
Keypom Trial Accounts are underway and we're developing a wallet selector module. The module will allow anyone with a specific link to be *instantly* signed into a dApp and immediately start signing transactions with *zero barrier to entry*.

A demo of this flow can be seen below:
https://user-images.githubusercontent.com/57506486/219454636-d69d6f14-1347-4160-81fd-e58681919192.mov

Currently, I'm manually hacking local storage in order to complete this (as seen in [this](https://github.com/keypom/ws-plugin/blob/341b823ea77ffc48e738a899056a228a8c5b3c22/src/lib/utils/keypom-lib.ts#L96-L115) function).

If the wallet selector were to update the way that wallets are "selected", it could potentially break things in our plugin.

It would be awesome if the `onWalletSignedIn` function found [here](https://github.com/near/wallet-selector/blob/7b8c36beaee1ef9eb47c7901a8cd60ad46921b16/packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts#L170-L209) could be exported and usable from within the Keypom module.

For some more context, the auto-sign in flow is called when the Keypom module is setup and when our `signIn` function is automatically invoked (if the URL is correct) - [here](https://github.com/keypom/ws-plugin/blob/341b823ea77ffc48e738a899056a228a8c5b3c22/src/lib/core/setup.ts#L41) and the actual auto signing in happens [here](https://github.com/keypom/ws-plugin/blob/341b823ea77ffc48e738a899056a228a8c5b3c22/src/lib/core/wallet.ts#L247). 

Instead of us manually hard-coding the sign in logic, I would like to use the one that the wallet selector uses such that if updates were to happen, we wouldn't have the rug pulled from beneath us.

**Comment by amirsaran3** [comment]
Hey@BenKurrek,

If I am understanding correctly you want to sign in to a wallet without interacting with the Wallet Selector Modal?

You can achieve this like this:
```ts
const wallet = (await _selector.store
      .getState()
      .modules[0].wallet()) as BrowserWallet;

wallet.signIn({
  contractId: CONTRACT_ID,
  methodNames: [],
});
```

I tested this in the NEAR Guest Book example. I used `_selector.store.getState().modules` to get the list of all modules and selectoed the first one since it is MyNearWallet in my example. Then I run the `.wallet()` function to get a wallet instance of that module. Then you can call `signIn()` on that wallet.

If you have any questions feel free to ask them or if this is not what you want can you clarify a bit.

**Comment by BenKurrek** [comment]
Hey @amirsaran3 thanks for the quick reply

I need to do this from *within* our own wallet module. For context, Keypom is creating a new "wallet" - the Keypom Wallet and we need to be able to instantly sign in users during the `setupKeypom` function. The selector is not exposed at this point

**Comment by amirsaran3** [comment]
> Hey @amirsaran3 thanks for the quick reply
> 
> I need to do this from _within_ our own wallet module. For context, Keypom is creating a new "wallet" - the Keypom Wallet and we need to be able to instantly sign in users during the `setupKeypom` function. The selector is not exposed at this point...

hey,

You can have a check for the url parameter inside the factory function and based on it call your `signIn()` function.

**Comment by amirsaran3** [comment]
@BenKurrek Do you still need help with this issue?

**Comment by BenKurrek** [comment]
> > Hey @amirsaran3 thanks for the quick reply
> > I need to do this from _within_ our own wallet module. For context, Keypom is creating a new "wallet" - the Keypom Wallet and we need to be able to instantly sign in users during the `setupKeypom` function. The selector is not exposed at this point...
> 
> hey,
> 
> You can have a check for the url parameter inside the factory function and based on it call your `signIn()` function.

@amirsaran3 this is what I'm doing right now. The problem is that I need the wallet selector to auto-sign in the user **without the app calling selector.signIn()**. This auto-sign in needs to happen on app load. I've achieved by "hacking" local storage as shown in links provided earlier. This is an issue though since I've hard-coded the logic and if the wallet selector changes how the login flow works with local storage, it will break my plugin. I've spoken with @MaximusHaximus about this issue and he suggested that the sign in flow be abstracted and callable from within the modules.

**Comment by amirsaran3** [comment]
@BenKurrek After talking with @MaximusHaximus I understand more about this issue.

You want to be able to sign in with wallet-selector without using the `@near-wallet-selector/modal-ui` package. The `@near-wallet-selector/core` package gives you access to sign into wallet modules like this: 
```ts
const wallet = await selector.store.getState().modules[0].wallet();
wallet.signIn({...});
```
You will need to add Keypom as a wallet module and then call the `signIn()` method like the above. The reason for this is that we rely on the `walletId`/`selectedWalletId`.

You were saying that you want us to expose the `onWalletSignedIn()` method and then you would be able to sign in. Inside the `onWalletSignedIn()` method we use the `walletId` parameter ([here](https://github.com/near/wallet-selector/blob/7b8c36beaee1ef9eb47c7901a8cd60ad46921b16/packages/core/src/lib/services/wallet-modules/wallet-modules.service.ts#L179)). You cannot just set the walletId/selectedWalletId to `"keypom"` and not have a keypom wallet module in the list of modules.

I assume that you would like us to expose some kind of method from the selector which you can use to manage the wallet-selector state. Something like this:
```ts
selector.signIn({ accounts: [...], contractId: "...", methodNames: [] });
```
The problem with this is that there is no indication to which wallet is being used to sign in. In your case you will only use wallet-selector to manage state. You will not be able to sign transactions and any other actions.

**Comment by amirsaran3** [comment]
@BenKurrek https://github.com/near/wallet-selector/pull/711 Here is just an example of how you can solve your issue.

I didn't create a separate package for the keypom. I just added the setup function directly to the angular example.

**Comment by BenKurrek** [comment]
@amirsaran3 sorry I've been AFK due to Eth Denver. Now that I'm back, I'd like to get back on this issue as it's an extremely high priority task that I'd love to get done before Consensus (end of april).

I do *not* want the app to have to call the Keypom's sign in function manually. As you can see in my example [here](https://github.com/keypom/ws-demo/blob/main/coin-flip/near-wallet.js#L38-L47), I am able to instantly sign in without needing to call `signIn()`. As mentioned before, this is done by manually changing the page's local storage [here](https://github.com/keypom/keypom-js/blob/main/src/lib/selector/utils/keypom-lib.ts#L94-L113).

Instead of me writing my own local storage logic to match the wallet selector, I need to be able to call an exported method from the wallet selector core. This is so that if the wallet selector changes how the sign in works, my wallet will not break.

**Comment by amirsaran3** [comment]
@BenKurrek Not signing in manually means that the user doesn't have to click anything. With the method above you can do that.

**Comment by AmmarHumackicSQA** [comment]
Hi @BenKurrek ,

If it would be more helpful, we can schedule a meeting to discuss this. 

We're mainly in the Central European Time (CET) zone, which is UTC+1

Please let us know if you'd like to proceed with a meeting. Thank you!

**Comment by BenKurrek** [comment]
Hi @AmmarHumackicSQA please schedule something on my calendly:

https://calendly.com/ben-kurrek

**Comment by BenKurrek** [comment]
@amirsaran3 hey I see you closed the PR

**Comment by BenKurrek** [comment]
> > @amirsaran3 hey I see you closed the PR
> 
> Hey @BenKurrek, You can check out this PR: #727.
> 
> We are making some changes. Once we merge this PR you will need to update your example with the new `InstantLinkWallet` type. and some other config stuff for your auto-signin feature to work.
> 
> If you have any questions feel free to ask them.

Awesomeee thanks so much y'all - let me know if I can help with testing the feature out. I'd be happy to hop on a call as well if it's easier for you.
