### ISSUE TITLE
Support NEP-413: `signMessage` Wallet Standard

### ISSUE THREAD

**Issue by frol** [near/wallet-selector#723]
**Is your feature request related to a problem? Please describe.**

See the motivation section in the [NEP-413](https://github.com/near/NEPs/blob/master/neps/nep-0413.md)

**Describe the solution you'd like**

Design and implement support of the `signMessage` API defined in the NEP-413.

**Additional context**

Wallets will need to implement the support from their side as well.

If there are any design or security concerns with the NEP-413, consider raising them in https://github.com/near/NEPs/pull/413

P.S. This issue [was highlighted through the DevGov Gigs Board](https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Post?id=279&referral=frol.near)

**Comment by AmmarHumackicSQA** [comment]
Hi @frol thanks for raising this issue. This is related to issue #434 and we are internally discussing with @MaximusHaximus how to approach it

**Comment by frol** [comment]
Closing in favor of #434.
