### ISSUE TITLE
walletconnect error - connection failed

### ISSUE THREAD

**Issue by sweetim** [near/wallet-selector#754]
**Describe the bug**
when `WalletConnect` is selected, it shows `Connection Failed`

```
Failed to sign in with WalletConnect: WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtmbVlYYXN4bnRRa2lKTEJVVGZmYkFzUUJXRE5xNE45RkZCWmJ2azFYQzRNSyIsInN1YiI6IjQ4MDI3ODlkMTlhZWNmYmQ1MTMwMDMxNjc5YmNmYmM1OTg2NTFlMDg1M2VjYzE2MTZlMmUzNDVmMzkyNmI1MTMiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY4MDUyNTM4NSwiZXhwIjoxNjgwNjExNzg1fQ.BNPhnxp3Fo_0qsef7_VKny5DbM-rQyoXeqnxDIAIxEv14K06iA5Xy1LnP-
```

**To Reproduce**
- use the code from the example from the guestbook

**Expected behavior**
able to connect to WalletConnect

**Screenshots**
![image](https://user-images.githubusercontent.com/6851767/229511665-3d2637ec-771e-474c-92a5-2dfc2e6037b5.png)

**Comment by kujtimprenkuSQA** [comment]
Hi, @sweetim thank you for raising this issue.

This is an expected behavior since the `projectId` is required for WalletConnect.

Docs: https://github.com/near/wallet-selector/tree/main/packages/wallet-connect#options

Sign up and create your own `projectid`: https://cloud.walletconnect.com/sign-in

**Comment by kujtimprenkuSQA** [comment]
@sweetim feel free to create any PR we would really appreciate any feedback or help 👍 

>Docs: https://github.com/near/wallet-selector/tree/main/packages/wallet-connect#options

Although this is mentioned in the main readme file of `wallet-connect` package many devs tend to miss reading it, maybe changing the value of [projectId](https://github.com/near/wallet-selector/blob/main/examples/react/contexts/WalletSelectorContext.tsx#L81) in the examples from "`c4f79cc...`" to `"YOUR_PROJECT_ID`" would make it clearer that this value is required.
