### ISSUE TITLE
enable support for near-api-js@"^2.0.4" and above?

### ISSUE THREAD

**Issue by sweetim** [near/wallet-selector#755]
*Describe the solution you'd like**
enable the package to support for `near-api-js@"^2.0.4"` version and above

currently when install the `@near-wallet-selector/core` package it will throw an error

```
└─▪ npm install @near-wallet-selector/core -S
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: timx-site@0.1.0
npm ERR! Found: near-api-js@2.0.4
npm ERR! node_modules/near-api-js
npm ERR!   near-api-js@"^2.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer near-api-js@"^0.44.2 || ^1.0.0" from @near-wallet-selector/core@7.9.2
npm ERR! node_modules/@near-wallet-selector/core
npm ERR!   @near-wallet-selector/core@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by kujtimprenkuSQA** [comment]
Hi, @sweetim thank you for raising this issue.

From our understanding, the goal with the newest version(s) of `near-api-js` is to split this package into [multiple small packages](https://github.com/near/near-api-js/tree/master/packages) we will work on this one but currently, there's no documentation on how to properly use these "separate" packages.

In the meantime, you can still use the `v1.1.0` of `near-api-js` in your dApp.

`yarn add near-api-js@1.1.0` or `npm install near-api-js@1.1.0`

If there are any errors or bugs with the `v1.1.0` of NAJ please let us know.

**Comment by AmmarHumackicSQA** [comment]
Hi @sweetim and thanks for raising this issue! I will close it for now, and if you have any additional questions feel free to reopen it.
