### ISSUE TITLE
Here wallet - can't sign in

### ISSUE THREAD

**Issue by Calcifer1001** [near/wallet-selector#908]
**Describe the bug**
When trying to sign in using Here wallet I get an error telling me I can't sign in. It doesn't even display the QR code that normally happens. I've seen this in 3 different websites

**To Reproduce**
1. Go to [metapool.app](https://www.metapool.app/stake?token=near)
2. Click on `Connect to stake`
3. Scroll down until you see `Here wallet`
4. Select `Here wallet`
5. See error `Failed to sign in with Here Wallet: Failed to fetch`

**Expected behavior**
On step 5, a QR code is expected to be shown so after scanning I can sign in (and later, sign transactions)

**Screenshots**
![image](https://github.com/near/wallet-selector/assets/83971551/2ab32387-171c-4abe-99c1-081443ae51f7)
![image](https://github.com/near/wallet-selector/assets/83971551/66b4a121-950e-4dda-909a-d838fe932ee4)

**Device (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Versión 116.0.5845.142 (Build oficial) (64 bits)

**Additional context**
The same error displays on near.social. On ref.finance is not working either, but they seem to have done something different on login, so no error is displayed on UI. I'm guessing is the same thing

**Comment by erditkurteshiSQA** [comment]
This issue is resolved and has been tested by the team. 
I will close the issue for now, if you have anything else please let us know.
