### ISSUE TITLE
NEP-141 (Non-NEAR FTs) Not Displaying On Wallet/s

### ISSUE THREAD

**Issue by trechriron** [near/wallet-selector#919]
### Description

This needs further discovery to understand the scope.

Several tickets report that user’s cannot see bridge exchanges on the NEAR Wallet. I’ve inquired with the Wallet Builders Group, but no one responded.

Does this impact all wallets or just NEAR Wallet?

What is the potential fix? Where will the fix need to happen?

Ammar Humackic 
June 29, 2023 at 5:55 AM

@Amir Saran addressed all the [comments](https://github.com/near/near-wallet/pull/3038#pullrequestreview-1498340452) left by @Daryl Collins on PR [#3038](https://github.com/near/near-wallet/pull/3038)

**Comment by AmmarHumackicSQA** [comment]
Will close this issue, as the PR [#3038](https://github.com/near/near-wallet/pull/3038) is open in another repo ([near/near-wallet](https://github.com/near/near-wallet/pull/3038)).
