### ISSUE TITLE
Update `explorerUrl` in Network presets to Nearblocks

### ISSUE THREAD

**Issue by kujtimprenkuSQA** [near/wallet-selector#966]
### Description

This task is to update the `explorerUrl` in Network presets:
https://github.com/near/wallet-selector/blob/main/packages/core/src/lib/options.ts#L5

New explorer URLs:

`mainnet`: https://nearblocks.io
`testnet`: https://testnet.nearblocks.io

The current Explorer will be deprecated: https://pages.near.org/blog/an-update-on-near-ecosystem-block-explorers

**Comment by kujtimprenkuSQA** [comment]
Hi, @diogoortega & @trechriron we are not sure about when we should update the URL for `explorerUrl` in the network prests, according to the article above it's mentioned that the "old" explorer will be deprecated on November 30, 2023. 

The only concern here is that if dApps are making use of the `explorerUrl` value of the wallet-selector's network presets then this update may cause broken links.

For example, ref-finance is already using the Nearblocks: https://github.com/ref-finance/ref-ui/blob/main/src/services/config.ts#L364 .

**Comment by diogoortega** [comment]
Hi @kujtimprenkuSQA, why could this update cause broken links? Because the URL scheme of the new explorer is different from the old one?

**Comment by diogoortega** [comment]
Got it, makes sense.
Since the old explorer will be deprecated, we need to make this change anyway. Let's do it now if we can.

**Comment by kujtimprenkuSQA** [comment]
Thanks, we will update them soon.
