### ISSUE TITLE
[Defect] Sign message using `near-wallet` navigates to 404 page

### ISSUE THREAD

**Issue by shelegdmitriy** [near/wallet-selector#973]
**Describe the bug**

At [near.org](https://near.org) we have a [/signMessage](https://near.org/signMessage) page to test such feature for supported wallets. At previous version of `wallet-selector` (in our case `8.5.1`) we've seen an alert explaining that some wallet doesn't support such method.

 After updating `wallet-selector` to the newest version and signing message with `near-wallet` navigates to 404 page.

**Steps To Reproduce**

_Steps to reproduce the behavior:_

1. Go to https://github.com/near/near-discovery/pull/736
2. Click on **"Visit Preview"** in vercel section ([link](https://github.com/near/near-discovery/pull/736#issuecomment-1771524574))
3. Log in to your account using near-wallet
4. Visit `/signMessage` page 
5. Add any message to the input and
6. Click **"Sign Message"** button 

_Whoops, looks like this page is missing._
Screenshot 2

**Expected behavior**

I'm expecting to see a confirm page on near-wallet or alert with text "The signMessage method is not supported by NEAR Wallet"

**Screenshots**
before update:

![wallet-selector-8-5-1](https://github.com/near/wallet-selector/assets/34593263/f97bc875-fb34-4ae9-8f8c-81bccdf64967)

after update:
<img width="1728" alt="Знімок екрана 2023-10-19 о 22 31 40" src="https://github.com/near/wallet-selector/assets/34593263/ec75449e-9c5f-49e3-84b7-04b522e17e4f">

**Desktop**: 
* OS : macOS Sonoma 14.0
* Browser : Brave Browser
* Browser Version : 1.59.120

**Comment by kujtimprenkuSQA** [comment]
Hi, @shelegdmitriy thank you for raising this issue.

It looks like when we added support for `signMessage` for the `my-near-wallet` it enabled this feature for `near-wallet` too in our side since the implementation of `near-wallet` in our repo just wraps around the `setupMyNearWallet`.

Since `near-wallet` does not support signMessage the right course of action would be to throw an error:

**The signMessage method is not supported by NEAR Wallet**

**Comment by kujtimprenkuSQA** [comment]
Hi, @shelegdmitriy we just published a new version of the wallet-selector, as mentioned above the best we can do on our side is to throw for wallets that do not support signMessage.

https://github.com/near/wallet-selector/releases/tag/v8.7.0

>Note This release introduces a new wallet to the wallet-selector `@near-wallet-selector/near-mobile-wallet` it also has support for signMessage.

**Comment by shelegdmitriy** [comment]
Thanks @kujtimprenkuSQA!

**Comment by kujtimprenkuSQA** [comment]
Keep in mind at the moment `signMessage` in MyNearWallet is supported only on `mainnet` until they merge the latest changes on the testnet environment, I pinged them here hopefully they will merge it soon: https://github.com/mynearwallet/my-near-wallet/pull/166#issuecomment-1772237204

**Comment by kujtimprenkuSQA** [comment]
> Keep in mind at the moment `signMessage` in MyNearWallet is supported only on `mainnet` until they merge the latest changes on the testnet environment, I pinged them here hopefully they will merge it soon: [mynearwallet/my-near-wallet#166 (comment)](https://github.com/mynearwallet/my-near-wallet/pull/166#issuecomment-1772237204)

Hi, @shelegdmitriy `signMessage` is now supported on `testnet` too.
